export const ErrorMessage = {
    NO_RECORD_FOUND: 'No record found',
    UPDATE_FAILED: 'Update failed',
    USER_NOT_FOUND: 'User not found',
    MOBILE_NUMBER_ALREADY_EXIST: 'Mobile number already exist',
    EMAIL_ID_ALREADY_EXIST: 'Email Id already exist',
    INVALID_OTP: 'Invalid otp',
    INVALID_INPUT: 'Invalid input',
    INVALID_LINK: 'Invalid link',
    EMAIL_NOT_UPDATED: 'Email updation failed, Please contact admin',
    MOBILE_NOT_UPDATED: 'Mobile updation failed, Please contact admin',
    INCORRECT_PASSWORD: 'Current password entered is incorrect',
    PASS_NOT_UPDATED: 'Error occurred while updating password.',
    CHANGE_PASSWORD_ERROR: 'There may be error occurred while changing password.',
    SAME_PASSWORD: 'Current and new password should not be same.',
    SESSIONS_ERROR: 'There may be error occurred while fetching sessions.',
    TECHNICAL_ERROR: 'Technical Error',
    LOGIN_ERROR: 'There may be error occurred while login',
    INVALID_CREDS: 'Please enter correct username/password',
    NOT_FOUND_BY_ID: 'No user found with this distributor id',
    LOGOUT_ERROR: 'There may be error occurred while logout',
    LOGOUT_ERROR_INSERT: 'Error occurred while logging out.',
    UNAUTHORIZED: 'User not authorized to see details',
    LOGIN_SETTING_UPDATE_ERROR: 'Some error occurred while updating login setting',
    USER_INACTIVE: 'User profile is disabled, please contact admin',
    GET_DISTRIBUTOR_LIST_ERROR: 'Get distributor List Error',
    ALERT_SETTINGS_UPDATE_ERROR: 'Some error occurred while updating alert settings',
    ALERT_SETTINGS_NOT_UPDATED: 'No alert setting provided to update',
    ALERT_HISTORY_UPDATE_ERROR: 'Some error occurred while adding alert remarks',
    DISTRIBUTOR_SETTINGS_UPDATE_ERROR: 'Some error occurred while updating distributor settings',
    COMMENT_LIST_ERROR: 'Some error occurred while getting comment list',
    PERMISSION_ISSUE: 'You are not permitted to access this resource',
    NO_ACCESS: `You don't have access to admin dashboard`,
    SSO_DETAILS_ERROR: 'Error occurred while fetching SSO user details',
    GET_TSE_LIST_ERROR: 'Error occurred while fetching list of tse user list',
    OTP_VERIFICATION_LIMIT_EXCEEDED_ERROR: 'You have exceeded number of attempts allowed for OTP verification, please try after',
    OTP_GENERATION_LIMIT_EXCEEDED_ERROR: 'Your limit for generating the OTP to reset password has reached, please try after',
    TSE_SETTING_UPDATE_ERROR: 'Error occurred while updating the tse user setting',
    TSE_ROLE_LOGIN_DELETED_REQUIRED: 'Please send either role or enableLogin or soft_delete field to update tse user setting',
    APP_LEVEL_SETTINGS_ERROR: 'Some error occurred while fetching app level settings',
    APP_LEVEL_SETTINGS_UPDATE_ERROR: 'Some error occurred while updating app level settings',
    APP_LEVEL_INVALID_CONFIG: 'is not a valid app level configuration setting',
    GET_ALERTS_ERROR: 'Some error occurred while fetching alerts details',
    UPDATE_ALERTS_ERROR: 'Some error occurred while updating alerts details',
    INVALID_REQUEST_BODY: 'Request body is invalid',
    ERROR_WHILE_FETCHING_CFA_DATA: 'Some error occuerred while fetching CFA data',
    FILE_NOT_FOUND: 'File not found',
    File_UPLOAD_ERROR: 'Some error occurred while uploading the file',
    FILE_HISTORY_ERROR: 'Some error occurred while fetching the file history',
    FILE_HISTORY_NOT_FOUND: 'file history not found',
    FILE_STATUS_UPDATE_ERROR: 'error while updating file status',
    GET_AZUREAD_USERS_DATA_ERROR: 'Error occured while fetching AzureAD Users data',
    SSO_USER_ERROR: 'Error while adding SSO User',
    SSO_USER_EXISTS: 'Failed to add user since email id exists',
    URL_NOT_EXIST: 'Error while creating pre assigned url',
    AREA_CODES_LIST_ERROR: 'Error in fetching area codes',
    GET_ADJUSTMENT_TIMELINE_ERROR: 'Error in fetching time line',
    FETCHED_STOCK_NORM_REGIONS_ERROR: 'Failed to fetch stock norm configuration regions',
    FETCHED_STOCK_NORM_AREAS_ERROR: 'Failed to fetch stock norm configuration areas',
    FETCHED_STOCK_NORM_DIVISIONS_ERROR: 'Failed to fetch stock norm configuration divisions',
    FETCHED_SAFETY_CYCLE_STOCK_ERROR: 'Failed to fetch cycle and safety stock data for stock norm configuration',
    UPDATED_SAFETY_CYCLE_STOCK_ERROR: 'Failed to update cycle and safety stock data for stock norm configuration',
    INSERT_CFA_DATA: 'Cfa data insert failed',
    UPDATED_CFA_DATA_ERROR: 'Cfa data updated failed',
    MULTIPLE_UPDATED_CFA_DATA_ERROR: 'Cfa data multiple update failed',
    FETCH_DB_MOQ_DATA: 'Failed to fetch db moq data',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    FETCH_DEPOT_LOGISTICS: 'Failed to fetch depot code for logistics',
    UPSERT_CFA_SURVEY_QUESTIONNAIRE: 'Failed to upsert CFA survey questionnaire',
    FETCH_CFA_SURVEY_QUESTIONS: 'Failed to fetch CFA survey questionnaire',
    SAVE_DB_RESPONSE: 'Failed to save distributor response to cfa survey',
    SURVEY_NOTIFICATION_ERROR: 'Error while sending survey notification',
    FETCH_SURVEY_REPORT_FOR_LOGISTICS: 'Error while fetching survey report for logistics',
    LIMIT_EXCEEDED: 'Failed Login Limit Exceeded',
    INVALIDATION_ERROR: 'Failed to invalidate session',
    INSERT_SESSION_LOG_ERROR: 'Error while inserting the session log',
    UPDATE_PDP_WINDOW: 'Failed to update PDP window',
    DELETE_PDP_EXCEPTION: 'Failed to delete PDP exception',
    INSERT_PDP_UNLOCK_REQUEST: 'Failed to insert PDP unlock request',
    FETCH_PDP_UNLOCK_REQUESTS: 'Failed to fetch PDP unlock requests',
    FETCH_DISTRIBUTOR_REGIONS: 'Failed to fetch distributor regions',
    UPDATE_PDP_UNLOCK_REQUEST: 'Failed to update PDP unlock request',
    FETCH_SSO_USERS: 'Failed to fetch SSO users',
    SYNC_PDP_UNLOCK_REQUESTS: 'Failed to sync PDP unlock requests',
    SET_EXPIRED_PDP_UNLOCK_REQUESTS: 'Failed to set expired PDP unlock requests',
    UNLOCK_PDP_BY_REQUEST: 'Failed to unlock PDP for the distributors in the given request_id',
    FETCH_PDP_WINDOW_SETTINGS: 'Failed to fetch PDP window settings',
    UPDATE_PDP_WINDOW_SETTINGS: 'Failed to update PDP Unlock window settings',
    LOCK_UNLOCK_PDP_BY_WINDOW: 'Failed to lock/unlock PDP based on PDP unlock window settings',
    FETCH_CFA_CALENDER_DATA: 'Failed to fetch CFA calender data',
    UPDATE_CFA_CALENDER_DATA: 'Failed to update process calendar',
    INVALIDATE_OTHER_SESSIONS: 'Failed to invalidate other sessions',
    INSERT_APPROVED_PDP_UNLOCK_REQUEST: 'Failed to insert approved PDP unlock request',
    FETCH_AUTO_CLOSURE_MT: 'Failed to fetch auto closure mt',
};
