export const SuccessMessage = {
    ALERT_UPDATED: 'Alert Updated Successfully',
    UPDATE_SUCCESS: 'Updated Successfully',
    DATA_FETCHED: 'Data Fetched Successfully',
    DATA_UPDATED: 'Data Updated',
    OTP_SEND_SUCESSFULLY: 'OTP Sent successfully',
    MOBILE_NUMBER_UPDATED_SUCESSFULLY: 'Mobile Number updated successfully',
    EMAIL_ID_UPDATED_SUCESSFULLY: 'Email Id updated successfully',
    MAIL_SENT: 'Email sent for verification, please check your email and verify',
    ALERT_INSERTED: 'Alert Inserted Successfully',
    PASS_UPDATED: 'Successfully updated the password.',
    FETCHED_SESSIONS: 'Successfully fetched the sessions.',
    LOGIN: 'User logged in successfully.',
    LOGOUT: 'User logged out successfully',
    DISTRIBUTION_LIST: 'Distributor List',
    LOGIN_SETTING_UPDATED: 'Login setting updated successfully',
    GET_ALERT: 'Get alert details',
    ALERT_SETTINGS_UPDATED: 'Alert settings updated successfully',
    ALERT_HISTORY_UPDATED: 'Alert remarks added successfully',
    DISTRIBUTOR_SETTINGS_UPDATED: 'Distributor settings updated successfully',
    COMMENT_LIST: 'Comment List',
    SSO_USER_DETAILS: 'Successfully fetched the SSO user details',
    TSE_LIST: 'Successfully fetched the tse user list',
    TSE_USER_SETTING_UPDATED: 'Tse user setting updated successfully',
    APP_LEVEL_SETTINGS_FETCHED: 'App level settings fetched successfully',
    APP_LEVEL_SETTINGS_UPDATED: 'App level settings updated successfully',
    GET_CFA_DATA_SUCCESS: 'CFA Data fetched successfully',
    HELP_DEST_FILE_UPLOAD_SUCCESS: 'File uploaded successfully',
    FILE_STATUS_UPDATE_SUCCESS: 'file status update successfull',
    GET_AZUREAD_USERS_DATA_SUCCESS: 'AzureAD Users Data fetched successfully',
    SSO_USER_ADDED_SUCCESSFUL: 'Successfully added SSO User',
    GET_HELP_SECTION_DATA_SUCCESS: 'Help section data fetched successfully',
    URL_CREATED_SUCCESS: 'Pre assigned url created successfully',
    AREA_CODES_LIST_SUCCESS: 'Area codes fetched successfully',
    GET_ADJUSTMENT_TIMELINE_SUCCESS: 'Timeline fetched successfully',
    FETCHED_STOCK_NORM_REGIONS_SUCCESS: 'Stock Norm configuration regions fetched successfully',
    FETCHED_STOCK_NORM_AREAS_SUCCESS: 'Stock Norm configuration areas fetched successfully',
    FETCHED_STOCK_NORM_DIVISIONS_SUCCESS: 'Stock Norm configuration divisions fetched successfully',
    FETCHED_SAFETY_CYCLE_STOCK_SUCCESS: 'Cycle and Safety stock data  fetched successfully',
    UPDATED_SAFETY_CYCLE_STOCK_SUCCESS: 'Cycle and Safety stock data  updated successfully',
    INSERT_CFA_DEPOT_MAPPING: 'Cfa data inserted successfully',
    UPDATED_CFA_DEPOT_MAPPING: 'Cfa data updated successfully',
    MULTIPLE_UPDATED_CFA_DEPOT_MAPPING: 'Cfa data multiple update successfully',
    FETCH_DB_MOQ_DATA: 'Distributor MOQ data fetched successfully',
    FETCH_DEPOT_LOGISTICS: 'Depot code for logistics fetched successfully',
    UPSERT_CFA_SURVEY_QUESTIONNAIRE: 'CFA survey questionnaire upserted successfully',
    FETCH_CFA_SURVEY_QUESTIONS: 'CFA survey questionnaire fetched successfully',
    SAVE_DB_RESPONSE: 'Distributor response  to cfa survey saved successfully',
    SURVEY_NOTIFICATION: 'Survey notification sent successfully',
    FETCH_SURVEY_REPORT: 'Survey report fetched successfully',
    FETCH_SURVEY_REPORT_FOR_LOGISTICS: 'Survey report for logistics fetched successfully',
    FETCH_ACTIVE_PLANT_DISTRIBUTORS: 'Fetched active plant distributors successfully',
    ACTIVE_SESSION_REPORT_FETCHED: 'Active session report fetched',
    USER_INVALIDATE: 'Session has been successfully invalidated',
    INSERT_SESSION_LOG: 'Session log has been inserted',
    FETCH_PDP_WINDOW: 'PDP window fetched successfully',
    UPDATE_PDP_WINDOW: 'PDP window updated successfully',
    DELETE_PDP_EXCEPTION: 'PDP exception deleted successfully',
    INSERT_PDP_UNLOCK_REQUEST: 'PDP unlock request has been inserted successfully',
    FETCH_PDP_UNLOCK_REQUESTS: 'PDP unlock requests fetched successfully',
    FETCH_DISTRIBUTOR_REGIONS: 'Distributor regions fetched successfully',
    UPDATE_PDP_UNLOCK_REQUEST: 'PDP unlock request updated successfully',
    FETCH_SSO_USERS: 'SSO users fetched successfully',
    SYNC_PDP_UNLOCK_REQUESTS: 'PDP unlock requests synced successfully',
    SET_EXPIRED_PDP_UNLOCK_REQUESTS: 'PDP unlock requests set expired successfully',
    REDIS_FLUSHED: 'Redis Flushed',
    UNLOCK_PDP_BY_REQUEST: 'PDP unlocked for the distributors in the given request_id successfully',
    FETCH_PDP_WINDOW_SETTINGS: 'PDP window settings fetched successfully',
    UPDATE_PDP_WINDOW_SETTINGS: 'PDP Unlock window settings updated successfully',
    LOCK_UNLOCK_PDP_BY_WINDOW: 'PDP locked/unlocked successfully based on PDP unlock window settings',
    SAVE_SURVEY_LINK: 'Survey link saved successfully',
    SAVE_NOC_RESPONSE: 'NOC response saved successfully',
    FETCH_DISTRIBUTORS_AGREEMENTS: 'Distributor agreements fetched successfully',
    FETCH_AUTO_CLOSURE_GT: 'Auto closure GT fetched successfully',
    FETCH_CFA_CALENDER_DATA: 'CFA calender data fetched successfully',
    UPDATE_CFA_CALENDER_DATA: 'CFA calender data updated successfully',
    INVALIDATE_OTHER_SESSIONS: 'Other sessions invalidated successfully',
    INSERT_APPROVED_PDP_UNLOCK_REQUEST: 'Approved PDP unlock request inserted successfully',
    SUBMIT_SURVEY: 'Survey response submitted successfully',
    FETCH_SURVEY_RESPONSES: 'Survey responses fetched successfully', 
    FETCH_AUTO_CLOSURE_MT: 'Auto closure MT fetched successfully',

};
