export const REDUX_RESET_STATE = 'REDUX_RESET_STATE';


// distributor constants
export const DISTRIBUTOR_UPDATE_CREATE_ORDER_FORM_FIELD = 'DISTRIBUTOR_UPDATE_CREATE_ORDER_FORM_FIELD';
export const DISTRIBUTOR_SUBMIT_CREATE_ORDER_FORM = 'DISTRIBUTOR_SUBMIT_CREATE_ORDER_FORM';
export const DISTRIBUTOR_VALIDATE_CREATE_ORDER_FORM = 'DISTRIBUTOR_VALIDATE_CREATE_ORDER_FORM';
export const DISTRIBUTOR_INVALIDATE_CREATE_ORDER_FORM = 'DISTRIBUTOR_INVALIDATE_CREATE_ORDER_FORM';
export const DISTRIBUTOR_RESET_CREATE_ORDER_FORM_FIELDS = 'DISTRIBUTOR_RESET_CREATE_ORDER_FORM_FIELDS';
export const DISTRIBUTOR_RESET_CREATE_ORDER_COMPLETE_FORM_FIELDS = 'DISTRIBUTOR_RESET_CREATE_ORDER_COMPLETE_FORM_FIELDS';
export const DISTRIBUTOR_RESET_CREATE_ORDER_FORM_FIELDS_FOR_LIQ_TOGGLE = 'DISTRIBUTOR_RESET_CREATE_ORDER_FORM_FIELDS_FOR_LIQ_TOGGLE';
export const DISTRIBUTOR_SET_MATERIALS_FIELD = 'DISTRIBUTOR_SET_MATERIALS_FIELD';
export const DISTRIBUTOR_SET_WAREHOUSES = 'DISTRIBUTOR_SET_WAREHOUSES';
export const LIQ_MATERIALS = 'LIQ_MATERIALS';
export const EXCLUDED_MATERIALS = 'EXCLUDED_MATERIALS';

// UI MODALS
export const UI_MODALS_UPDATE_FIELD = 'UI_MODALS_UPDATE_FIELD';
export const UI_PROCESSING_UPDATE_FIELD = 'UI_PROCESSING_UPDATE_FIELD';
export const UI_LOADED_UPDATE_FIELD = 'UI_LOADED_UPDATE_FIELD';

// app constants
export const APP_CONFIG_TOGGLE_ASIDE = 'APP_CONFIG_TOGGLE_ASIDE';
export const INITIATE_LOADING = 'INITIATE_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const UPDATE_FIELD = 'UPDATE_FIELD';
export const UPDATE_SECTION = 'UPDATE_SECTION';
export const UPDATE_TABS = 'UPDATE_TABS';
export const UPDATE_LOADED = 'UPDATE_LOADED';
export const SET_MESSAGES = 'SET_MESSAGES';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const SET_USER_LANGUAGE = 'SET_USER_LANGUAGE';

export const FORECAST_FOR_DIST = "FORECAST_FOR_DIST";

