import unittest
from unittest.mock import patch
from src.transformers.bigbasket_transformers import BigBasketTransformers
from src.models.dto.po_dto import PoDTO, PoItemsDTO
from datetime import date, datetime


class TestBigBasketTransformers(unittest.TestCase):

    def setUp(self):
        self.transformer = BigBasketTransformers()

    @patch("src.services.data_persist_service.DataPersistService.get_customer_code")
    def test_po_transformer(self, mock_get_customer_code):
        payload = {
            "PurchaseOrder": {
                "Header": {
                    "TransmissionDate": "07/02/2025",
                    "PurchaseOrderNumber": "637369",
                    "PODate": "07/02/2025",
                    "ExpiryDate": "28/02/2025",
                    "TypeCode": "3",
                    "PurposeCode": "00621",
                    "Number": "BBHYD002",
                    "CustomerGSTIN": "36AACCI2053A1Z8",
                },
                "ItemDetails": {
                    "Item": [
                        {
                            "LineNumber": "1",
                            "ItemFlags": "",
                            "HSNCode": "21011110",
                            "SkuCode": "40279032",
                            "Description": "Tata Coffee Grand Classic Instant Coffee 7 g Pouch",
                            "EAN": "8901090328123",
                            "UOM": "336",
                            "Quantity": "336",
                            "BasicCost": "7.03",
                            "SGSTPercent": "9",
                            "SGST": "212.59",
                            "CGSTPercent": "9",
                            "CGST": "212.59",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "425.17",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "8.3",
                            "MRP": "10",
                            "TotalValue": "2788.8",
                        },
                        {
                            "LineNumber": "2",
                            "ItemFlags": "",
                            "HSNCode": "21011110",
                            "SkuCode": "40279035",
                            "Description": "Tata Coffee Grand Classic Instant Coffee 200 g Pouch",
                            "EAN": "8901090328581",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "393.9",
                            "SGSTPercent": "9",
                            "SGST": "425.41",
                            "CGSTPercent": "9",
                            "CGST": "425.41",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "850.82",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "464.8",
                            "MRP": "560",
                            "TotalValue": "5577.6",
                        },
                        {
                            "LineNumber": "3",
                            "ItemFlags": "",
                            "HSNCode": "9021030",
                            "SkuCode": "40279037",
                            "Description": "Tata Tea Gold Saffron Black Tea Natural Flavour Rich In Taste 100 g",
                            "EAN": "8901052006199",
                            "UOM": "120",
                            "Quantity": "120",
                            "BasicCost": "66.37",
                            "SGSTPercent": "2.5",
                            "SGST": "199.11",
                            "CGSTPercent": "2.5",
                            "CGST": "199.11",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "398.22",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "69.69",
                            "MRP": "85",
                            "TotalValue": "8362.801",
                        },
                        {
                            "LineNumber": "4",
                            "ItemFlags": "",
                            "HSNCode": "19022090",
                            "SkuCode": "40279423",
                            "Description": "Tata Sampann Yumside Cheesy Pasta With Corn 285 g",
                            "EAN": "8904043905624",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "86.38",
                            "SGSTPercent": "6",
                            "SGST": "62.19",
                            "CGSTPercent": "6",
                            "CGST": "62.19",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "124.39",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "96.75",
                            "MRP": "129",
                            "TotalValue": "1161",
                        },
                        {
                            "LineNumber": "5",
                            "ItemFlags": "",
                            "HSNCode": "19022090",
                            "SkuCode": "40279427",
                            "Description": "Tata Sampann Yumside Schezwan Noodles With Veggies 285 g",
                            "EAN": "8904043905662",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "86.38",
                            "SGSTPercent": "6",
                            "SGST": "62.19",
                            "CGSTPercent": "6",
                            "CGST": "62.19",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "124.39",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "96.75",
                            "MRP": "129",
                            "TotalValue": "1161",
                        },
                        {
                            "LineNumber": "6",
                            "ItemFlags": "",
                            "HSNCode": "21069099",
                            "SkuCode": "40279429",
                            "Description": "Tata Sampann Yumside Vegetable Biryani 330 g",
                            "EAN": "8904043905686",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "81.99",
                            "SGSTPercent": "9",
                            "SGST": "88.55",
                            "CGSTPercent": "9",
                            "CGST": "88.55",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "177.1",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "96.75",
                            "MRP": "129",
                            "TotalValue": "1161",
                        },
                        {
                            "LineNumber": "7",
                            "ItemFlags": "",
                            "HSNCode": "21061000",
                            "SkuCode": "40279432",
                            "Description": "Tata GoFit Plant Protein Powder - Rich Chocolate F 1 kg  ((40 Serves))",
                            "EAN": "8904043905358",
                            "UOM": "4",
                            "Quantity": "4",
                            "BasicCost": "1890.92",
                            "SGSTPercent": "9",
                            "SGST": "680.73",
                            "CGSTPercent": "9",
                            "CGST": "680.73",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "1361.46",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "2231.28",
                            "MRP": "3099",
                            "TotalValue": "8925.12",
                        },
                        {
                            "LineNumber": "8",
                            "ItemFlags": "",
                            "HSNCode": "9021010",
                            "SkuCode": "40283638",
                            "Description": "Tata Tea Gemini  Black Tea - Rich In Taste & Aroma 1 kg PET Jar",
                            "EAN": "8901052021178",
                            "UOM": "6",
                            "Quantity": "12",
                            "BasicCost": "437.33",
                            "SGSTPercent": "2.5",
                            "SGST": "131.2",
                            "CGSTPercent": "2.5",
                            "CGST": "131.2",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "262.4",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "459.2",
                            "MRP": "560",
                            "TotalValue": "5510.4",
                        },
                        {
                            "LineNumber": "9",
                            "ItemFlags": "",
                            "HSNCode": "16023200",
                            "SkuCode": "40283729",
                            "Description": "Tata Sampann Yumside Spicy Chicken Tikka Sausage 180 g",
                            "EAN": "8904043905709",
                            "UOM": "24",
                            "Quantity": "24",
                            "BasicCost": "86.38",
                            "SGSTPercent": "6",
                            "SGST": "124.39",
                            "CGSTPercent": "6",
                            "CGST": "124.39",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "248.77",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "96.75",
                            "MRP": "129",
                            "TotalValue": "2322",
                        },
                        {
                            "LineNumber": "10",
                            "ItemFlags": "",
                            "HSNCode": "16023200",
                            "SkuCode": "40283730",
                            "Description": "Tata Sampann Yumside Classic Chicken Seekh Kebab 180 g",
                            "EAN": "8904043905716",
                            "UOM": "24",
                            "Quantity": "24",
                            "BasicCost": "86.61",
                            "SGSTPercent": "6",
                            "SGST": "124.72",
                            "CGSTPercent": "6",
                            "CGST": "124.72",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "249.44",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "97",
                            "MRP": "129",
                            "TotalValue": "2328",
                        },
                        {
                            "LineNumber": "11",
                            "ItemFlags": "",
                            "HSNCode": "21069099",
                            "SkuCode": "40283731",
                            "Description": "Tata Sampann Yumside Delhi Style Dal Makhani 285 g",
                            "EAN": "8904043905730",
                            "UOM": "24",
                            "Quantity": "24",
                            "BasicCost": "81.99",
                            "SGSTPercent": "9",
                            "SGST": "177.1",
                            "CGSTPercent": "9",
                            "CGST": "177.1",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "354.2",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "96.75",
                            "MRP": "129",
                            "TotalValue": "2322",
                        },
                        {
                            "LineNumber": "12",
                            "ItemFlags": "",
                            "HSNCode": "21069099",
                            "SkuCode": "40283732",
                            "Description": "Tata Sampann Yumside Amritsari Style Chana Masala 285 g",
                            "EAN": "8904043905747",
                            "UOM": "6",
                            "Quantity": "12",
                            "BasicCost": "75.64",
                            "SGSTPercent": "9",
                            "SGST": "81.69",
                            "CGSTPercent": "9",
                            "CGST": "81.69",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "163.38",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "89.25",
                            "MRP": "119",
                            "TotalValue": "1071",
                        },
                        {
                            "LineNumber": "13",
                            "ItemFlags": "",
                            "HSNCode": "21069099",
                            "SkuCode": "40283733",
                            "Description": "Tata Sampann Yumside Delhi Style Paneer Makhani 285 g",
                            "EAN": "8904043905754",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "98.52",
                            "SGSTPercent": "9",
                            "SGST": "106.4",
                            "CGSTPercent": "9",
                            "CGST": "106.4",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "212.8",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "116.25",
                            "MRP": "155",
                            "TotalValue": "1395",
                        },
                        {
                            "LineNumber": "14",
                            "ItemFlags": "",
                            "HSNCode": "21069099",
                            "SkuCode": "40283734",
                            "Description": "Tata Sampann Yumside , 285 g",
                            "EAN": "8904043905761",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "132.84",
                            "SGSTPercent": "9",
                            "SGST": "143.47",
                            "CGSTPercent": "9",
                            "CGST": "143.47",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "286.93",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "156.75",
                            "MRP": "209",
                            "TotalValue": "1881",
                        },
                        {
                            "LineNumber": "15",
                            "ItemFlags": "",
                            "HSNCode": "21033000",
                            "SkuCode": "40283736",
                            "Description": "Tata Sampann Yumside Punjabi Style Makhani Gravy 180 g",
                            "EAN": "8904043905785",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "86.38",
                            "SGSTPercent": "6",
                            "SGST": "62.19",
                            "CGSTPercent": "6",
                            "CGST": "62.19",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "124.39",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "96.74",
                            "MRP": "129",
                            "TotalValue": "1160.88",
                        },
                        {
                            "LineNumber": "16",
                            "ItemFlags": "",
                            "HSNCode": "21033000",
                            "SkuCode": "40283738",
                            "Description": "Tata Sampann Yumside Thanjavur Style Sambar Paste - Ready To Co 150 g",
                            "EAN": "8904043905808",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "79.69",
                            "SGSTPercent": "6",
                            "SGST": "57.38",
                            "CGSTPercent": "6",
                            "CGST": "57.38",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "114.75",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "89.25",
                            "MRP": "119",
                            "TotalValue": "1071",
                        },
                        {
                            "LineNumber": "17",
                            "ItemFlags": "",
                            "HSNCode": "21033000",
                            "SkuCode": "40283739",
                            "Description": "Tata Sampann Yumside Hyderabadi Style Biryani Paste - Ready To  150 g",
                            "EAN": "8904043905815",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "86.38",
                            "SGSTPercent": "6",
                            "SGST": "62.19",
                            "CGSTPercent": "6",
                            "CGST": "62.19",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "124.39",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "96.75",
                            "MRP": "129",
                            "TotalValue": "1161",
                        },
                        {
                            "LineNumber": "18",
                            "ItemFlags": "",
                            "HSNCode": "9021010",
                            "SkuCode": "40284111",
                            "Description": "Tetley Green Tea - Immune Tulsi, With A 30 g  ((25 Bags x 1.2 g Each))",
                            "EAN": "8901052006359",
                            "UOM": "36",
                            "Quantity": "36",
                            "BasicCost": "138",
                            "SGSTPercent": "2.5",
                            "SGST": "124.2",
                            "CGSTPercent": "2.5",
                            "CGST": "124.2",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "248.4",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "144.9",
                            "MRP": "180",
                            "TotalValue": "5216.4",
                        },
                        {
                            "LineNumber": "19",
                            "ItemFlags": "",
                            "HSNCode": "25010020",
                            "SkuCode": "40285883",
                            "Description": "Tata Salt Pink Salt For Everyday Cooking 1 kg Pouch",
                            "EAN": "8904043905457",
                            "UOM": "12",
                            "Quantity": "348",
                            "BasicCost": "64",
                            "SGSTPercent": "0",
                            "SGST": "0",
                            "CGSTPercent": "0",
                            "CGST": "0",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "0",
                            "GSTAmount": "0",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "64",
                            "MRP": "80",
                            "TotalValue": "22272",
                        },
                        {
                            "LineNumber": "20",
                            "ItemFlags": "",
                            "HSNCode": "9023020",
                            "SkuCode": "40287568",
                            "Description": "Tata Tea Premium Street Chai Of India - Kolkata Street Chai, Ta 250 g",
                            "EAN": "8901052006571",
                            "UOM": "48",
                            "Quantity": "48",
                            "BasicCost": "113.24",
                            "SGSTPercent": "2.5",
                            "SGST": "135.89",
                            "CGSTPercent": "2.5",
                            "CGST": "135.89",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "271.78",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "118.9",
                            "MRP": "145",
                            "TotalValue": "5707.2",
                        },
                        {
                            "LineNumber": "21",
                            "ItemFlags": "",
                            "HSNCode": "9109100",
                            "SkuCode": "40288886",
                            "Description": "Tata Sampann Sambar Masala - Authentic Taste Of South India, Ar 100 g",
                            "EAN": "8904043905129",
                            "UOM": "180",
                            "Quantity": "180",
                            "BasicCost": "56.67",
                            "SGSTPercent": "2.5",
                            "SGST": "255.01",
                            "CGSTPercent": "2.5",
                            "CGST": "255.01",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "510.03",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "59.5",
                            "MRP": "85",
                            "TotalValue": "10710",
                        },
                        {
                            "LineNumber": "22",
                            "ItemFlags": "",
                            "HSNCode": "7139010",
                            "SkuCode": "40289046",
                            "Description": "Tata Sampann Unpolished Toor Dal/Arhar Dal 5 kg",
                            "EAN": "8904043901916",
                            "UOM": "4",
                            "Quantity": "4",
                            "BasicCost": "687.02",
                            "SGSTPercent": "2.5",
                            "SGST": "68.7",
                            "CGSTPercent": "2.5",
                            "CGST": "68.7",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "137.4",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "721.37",
                            "MRP": "995",
                            "TotalValue": "2885.48",
                        },
                        {
                            "LineNumber": "23",
                            "ItemFlags": "",
                            "HSNCode": "8062010",
                            "SkuCode": "40289767",
                            "Description": "Tata Sampann 100% Pure Afghani Black Raisins/Kali Kishmish - Se 200 g",
                            "EAN": "8904043906362",
                            "UOM": "54",
                            "Quantity": "54",
                            "BasicCost": "178.29",
                            "SGSTPercent": "2.5",
                            "SGST": "240.69",
                            "CGSTPercent": "2.5",
                            "CGST": "240.69",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "481.38",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "187.2",
                            "MRP": "240",
                            "TotalValue": "10108.8",
                        },
                        {
                            "LineNumber": "24",
                            "ItemFlags": "",
                            "HSNCode": "21011110",
                            "SkuCode": "40300028",
                            "Description": "Tata Coffee Classic Cold Coffee 400 ml Box ((20 Sachets x 20 ml Each))",
                            "EAN": "8901052006731",
                            "UOM": "6",
                            "Quantity": "6",
                            "BasicCost": "343.22",
                            "SGSTPercent": "9",
                            "SGST": "185.34",
                            "CGSTPercent": "9",
                            "CGST": "185.34",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "370.68",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "405",
                            "MRP": "500",
                            "TotalValue": "2430",
                        },
                        {
                            "LineNumber": "25",
                            "ItemFlags": "",
                            "HSNCode": "21011110",
                            "SkuCode": "40300029",
                            "Description": "Tata Coffee Choco Mocha Cold Co 400 ml Box ((20 Sachets x 20 ml Each))",
                            "EAN": "8901052006748",
                            "UOM": "6",
                            "Quantity": "6",
                            "BasicCost": "343.22",
                            "SGSTPercent": "9",
                            "SGST": "185.34",
                            "CGSTPercent": "9",
                            "CGST": "185.34",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "370.68",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "405",
                            "MRP": "500",
                            "TotalValue": "2430",
                        },
                        {
                            "LineNumber": "26",
                            "ItemFlags": "",
                            "HSNCode": "21011110",
                            "SkuCode": "40300030",
                            "Description": "Tata Coffee Salted Caramel Cold 400 ml Box ((20 Sachets x 20 ml Each))",
                            "EAN": "8901052006755",
                            "UOM": "6",
                            "Quantity": "6",
                            "BasicCost": "343.22",
                            "SGSTPercent": "9",
                            "SGST": "185.34",
                            "CGSTPercent": "9",
                            "CGST": "185.34",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "370.68",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "405",
                            "MRP": "500",
                            "TotalValue": "2430",
                        },
                        {
                            "LineNumber": "27",
                            "ItemFlags": "",
                            "HSNCode": "21069099",
                            "SkuCode": "40300031",
                            "Description": "Tata Sampann Fibre Rich Idli Mix - Ready to Cook Breakfast Mix, 500 g",
                            "EAN": "8904043906096",
                            "UOM": "1",
                            "Quantity": "2",
                            "BasicCost": "88.98",
                            "SGSTPercent": "9",
                            "SGST": "16.02",
                            "CGSTPercent": "9",
                            "CGST": "16.02",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "32.03",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "105",
                            "MRP": "140",
                            "TotalValue": "210",
                        },
                        {
                            "LineNumber": "28",
                            "ItemFlags": "",
                            "HSNCode": "20079990",
                            "SkuCode": "40300965",
                            "Description": "Himalayan Elevation Black Cherry Preserve 240 g",
                            "EAN": "8903754000468",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "162.29",
                            "SGSTPercent": "6",
                            "SGST": "116.85",
                            "CGSTPercent": "6",
                            "CGST": "116.85",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "233.7",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "181.77",
                            "MRP": "249",
                            "TotalValue": "2181.24",
                        },
                        {
                            "LineNumber": "29",
                            "ItemFlags": "",
                            "HSNCode": "19041090",
                            "SkuCode": "40300970",
                            "Description": "Tata Soulfull Millet Granola Breakfast Cereal - Honey, Fruits,  400 g",
                            "EAN": "8906113491020",
                            "UOM": "18",
                            "Quantity": "18",
                            "BasicCost": "228.81",
                            "SGSTPercent": "9",
                            "SGST": "370.67",
                            "CGSTPercent": "9",
                            "CGST": "370.67",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "741.34",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "270",
                            "MRP": "375",
                            "TotalValue": "4860",
                        },
                        {
                            "LineNumber": "30",
                            "ItemFlags": "",
                            "HSNCode": "19041090",
                            "SkuCode": "40302721",
                            "Description": "Tata Soulfull Nutri Drink+ For Kids - With Millets, Chocolat 200 g Box",
                            "EAN": "8906113491037",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "91.53",
                            "SGSTPercent": "9",
                            "SGST": "98.85",
                            "CGSTPercent": "9",
                            "CGST": "98.85",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "197.7",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "108",
                            "MRP": "150",
                            "TotalValue": "1296",
                        },
                        {
                            "LineNumber": "31",
                            "ItemFlags": "",
                            "HSNCode": "19023090",
                            "SkuCode": "40302723",
                            "Description": "Tata Sampann Yumside Classic Mac & Cheese Pasta 285 g",
                            "EAN": "8904043906232",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "86.38",
                            "SGSTPercent": "6",
                            "SGST": "62.19",
                            "CGSTPercent": "6",
                            "CGST": "62.19",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "124.39",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "96.75",
                            "MRP": "129",
                            "TotalValue": "1161",
                        },
                        {
                            "LineNumber": "32",
                            "ItemFlags": "",
                            "HSNCode": "21069099",
                            "SkuCode": "40302724",
                            "Description": "Tata Sampann Yumside Schezwan Fried Rice - Bold & Spicy, Ready  330 g",
                            "EAN": "8904043906249",
                            "UOM": "12",
                            "Quantity": "12",
                            "BasicCost": "81.99",
                            "SGSTPercent": "9",
                            "SGST": "88.55",
                            "CGSTPercent": "9",
                            "CGST": "88.55",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "177.1",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "96.75",
                            "MRP": "129",
                            "TotalValue": "1161",
                        },
                        {
                            "LineNumber": "33",
                            "ItemFlags": "",
                            "HSNCode": "9021090",
                            "SkuCode": "40303127",
                            "Description": "Tata Tea Chakra Gold Premium Leaf Tea 500 g",
                            "EAN": "8901052006816",
                            "UOM": "24",
                            "Quantity": "24",
                            "BasicCost": "367.05",
                            "SGSTPercent": "2.5",
                            "SGST": "220.23",
                            "CGSTPercent": "2.5",
                            "CGST": "220.23",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "440.46",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "385.4",
                            "MRP": "470",
                            "TotalValue": "9249.6",
                        },
                        {
                            "LineNumber": "34",
                            "ItemFlags": "",
                            "HSNCode": "12079990",
                            "SkuCode": "40312410",
                            "Description": "Tata Sampann 100% Pure Premium Chia Seeds 200 g",
                            "EAN": "8904043906584",
                            "UOM": "50",
                            "Quantity": "50",
                            "BasicCost": "151.28",
                            "SGSTPercent": "2.5",
                            "SGST": "189.1",
                            "CGSTPercent": "2.5",
                            "CGST": "189.1",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "378.2",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "158.84",
                            "MRP": "209",
                            "TotalValue": "7942",
                        },
                        {
                            "LineNumber": "35",
                            "ItemFlags": "",
                            "HSNCode": "21011200",
                            "SkuCode": "40313026",
                            "Description": "Tata Coffee Quick Filter Decoction Liquid, Degree Kaapi, Decoc 200 ml",
                            "EAN": "8901052007189",
                            "UOM": "30",
                            "Quantity": "30",
                            "BasicCost": "142.37",
                            "SGSTPercent": "9",
                            "SGST": "384.4",
                            "CGSTPercent": "9",
                            "CGST": "384.4",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "768.8",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "168",
                            "MRP": "200",
                            "TotalValue": "5040",
                        },
                        {
                            "LineNumber": "36",
                            "ItemFlags": "",
                            "HSNCode": "8029000",
                            "SkuCode": "40313337",
                            "Description": "Tata Sampann High Protein Makhana 100 g",
                            "EAN": "8904043906515",
                            "UOM": "36",
                            "Quantity": "36",
                            "BasicCost": "149.14",
                            "SGSTPercent": "2.5",
                            "SGST": "134.23",
                            "CGSTPercent": "2.5",
                            "CGST": "134.23",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "268.45",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "156.6",
                            "MRP": "270",
                            "TotalValue": "5637.6",
                        },
                        {
                            "LineNumber": "37",
                            "ItemFlags": "",
                            "HSNCode": "8041090",
                            "SkuCode": "40313338",
                            "Description": "Tata Sampann High Protein Makhana 200 g",
                            "EAN": "8904043906522",
                            "UOM": "18",
                            "Quantity": "18",
                            "BasicCost": "279.64",
                            "SGSTPercent": "6",
                            "SGST": "302.01",
                            "CGSTPercent": "6",
                            "CGST": "302.01",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "604.02",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "313.2",
                            "MRP": "540",
                            "TotalValue": "5637.6",
                        },
                        {
                            "LineNumber": "38",
                            "ItemFlags": "",
                            "HSNCode": "21069099",
                            "SkuCode": "40313840",
                            "Description": "Tata Sampann Gulab Jamun Dessert Mix 175 g  ((Buy 1 Get 1 Free))",
                            "EAN": "8904043906843",
                            "UOM": "1",
                            "Quantity": "2",
                            "BasicCost": "92.16",
                            "SGSTPercent": "9",
                            "SGST": "16.59",
                            "CGSTPercent": "9",
                            "CGST": "16.59",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "18",
                            "GSTAmount": "33.18",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "108.75",
                            "MRP": "145",
                            "TotalValue": "217.5",
                        },
                        {
                            "LineNumber": "39",
                            "ItemFlags": "",
                            "HSNCode": "9021030",
                            "SkuCode": "40314645",
                            "Description": "Tetley Premium Black Leaf Tea 250 g",
                            "EAN": "8901052007349",
                            "UOM": "48",
                            "Quantity": "48",
                            "BasicCost": "183.52",
                            "SGSTPercent": "2.5",
                            "SGST": "220.22",
                            "CGSTPercent": "2.5",
                            "CGST": "220.22",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "5",
                            "GSTAmount": "440.45",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "192.7",
                            "MRP": "235",
                            "TotalValue": "9249.6",
                        },
                        {
                            "LineNumber": "40",
                            "ItemFlags": "",
                            "HSNCode": "22029930",
                            "SkuCode": "40314866",
                            "Description": "Tata Coffee Gold Classic Flavoured Cold Brew Rich & Creamy Rea 200 ml",
                            "EAN": "8903754000369",
                            "UOM": "18",
                            "Quantity": "18",
                            "BasicCost": "80.36",
                            "SGSTPercent": "6",
                            "SGST": "86.79",
                            "CGSTPercent": "6",
                            "CGST": "86.79",
                            "IGSTPercent": "0",
                            "IGST": "0",
                            "GSTPercent": "12",
                            "GSTAmount": "173.58",
                            "CessPercent": "0",
                            "CessValue": "0",
                            "UnitCessPerPiece": "0",
                            "CessPerPieceValue": "0",
                            "LandingCost": "90",
                            "MRP": "125",
                            "TotalValue": "1620",
                        },
                    ]
                },
                "Trailer": "",
            }
        }
        location = "test_location"
        mock_get_customer_code.return_value = {"customer_code": "123"}

        po_dto = self.transformer.po_transformer(payload, location)

        self.assertIsInstance(po_dto, PoDTO)
        self.assertEqual(po_dto.vendor_code, "621")
        self.assertEqual(po_dto.po_number, "637369")
        self.assertEqual(po_dto.po_created_date, date(2025, 2, 7))
        self.assertEqual(po_dto.delivery_date.date(), date(2025, 2, 28))
        self.assertEqual(po_dto.customer_code, "123")
        self.assertEqual(po_dto.site_code, "BBHYD002")
        self.assertEqual(len(po_dto.items), 40)
        self.assertIsInstance(po_dto.items[0], PoItemsDTO)


if __name__ == "__main__":
    unittest.main()
