// dashboard constants
export const DASHBOARD_SET_ALL_MATERIALS = 'DASHBOARD_SET_ALL_MATERIALS';
export const DASHBOARD_ORDER_LIST = 'DASHBOARD_ORDER_LIST';
export const DASHBOARD_SET_WAREHOUSES = 'DASHBOARD_SET_WAREHOUSES';
export const DASHBOARD_REGION_DETAILS = 'DASHBOARD_REGION_DETAILS';
export const DASHBOARD_PO_DETAILS = 'DASHBOARD_PO_DETAILS';
export const ALERT_DETAILS = 'ALERT_DETAILS';
export const DASHBOARD_CREDIT_DETAILS = 'DASHBOARD_CREDIT_DETAILS';
export const ORDER_DEATILS_HEADER_DATA = 'ORDER_DEATILS_HEADER_DATA';
// export const DASHBOARD_PO_DETAILS_LOADING = 'DASHBOARD_PO_DETAILS_LOADING';
export const ALERT_COMMENT_LIST = 'ALERT_COMMENT_LIST';
export const ADJUSTMENT_TIMELINE = "ADJUSTMENT_TIMELINE";
