//Service_delivery_request constants
export const SERVICE_DELIVERY_REQUEST_LIST='SERVICE_DELIVERY_REQUEST_LIST';
export const ADD_SERVICE_DELIVERY_REQUEST='ADD_SERVICE_DELIVERY_REQUEST';
export const UPADTE_CFA_RESPONSE = 'UPADTE_CFA_RESPONSE';