export const ErrorMessage = {
    'UPDATE_MATERIAL_TAGS_ERROR': 'Some error occurred while updating material tags',
    'UPSERT_SALES_HIERARCHY_DETAILS_ERROR': 'Some error occurred while upserting sales hierarchy details',
    'PERMISSION_ISSUE': 'You are not permitted to access this resource',
    'SYNC_LOGS_FETCHED_ERROR': 'Some error occurred while fetching sync logs',
    'SYNC_LOGS_ERROR': 'There may be error occurred while fetching sync logs',
    'MATERIALS_TAG_FETCHED_ERROR': 'Some error occurred while fetching Materials tags ',
    'MATERIALS_TAG_ERROR': 'There may be error occurred while fetching Materials tags ',
    'REMOVE_DRAFT_ERROR': 'Some error occurred while removing your cart',
    'REMOVE_EXPIRED_CARTS_ERROR': 'Some error occurred while removing the expired carts of the distributor',
    'CART_EXPIRY_WINDOW_NOT_FOUND': 'Cart expiry window limit is not found in the app level settings',
    'ZONE_WISE_ORDER_ERROR': 'Some error occurred while fetching zone wise orders',
    'CATEGORY_WISE_ISSUES_ERROR': 'Some error occurred while fetching category wise reported issues',
    'GET_SDR_LIST_ERROR': 'Error occurred while retrieving service delivery request',
    'GET_SDR_REPORT_DATA_ERROR': 'Error occurred while fetching SDR Report data',
    'GET_SD_RESPONSE_REPORT_DATA_ERROR': 'Error occurred while fetching SD Response Report data',
    'BRAND_VARIANT_LIST_ERROR': 'Error occurred while fetching brand variant list',
    'GET_FORECAST_ERROR': 'Error occurred while fetching forecast data',
    'REGIONAL_BRAND_LIST_ERROR': 'Error occurred while fetching regional brand list',
    'UPDATE_FORECAST': 'Error occurred while updating forecast data',
    'FORECAST_CONFIGURATIONS_LIST_ERROR': 'Error in fetching forecast configurations list',
    'FORECAST_CONFIGURATION_UPDATE_ERROR': 'Error in updating the forecast configuration',
    'GET_FORECAST_SUMMARY_ERROR': 'Error occurred while fetching forecast summary data',
    'INTERNAL_SERVER_ERROR': 'Internal server error',
    'UPSERT_FORECAST_DISTRIBUTION_ERROR': 'Error occurred during upsert of forecast distribution. Please contact Administrator',
    'VALIDATION_ERRORS': 'Error in validating # field',
    'SUGGESTED_MATERIAL_FETCH_ERROR': 'No recommendations available for Auto-Order. Please place Regular-Order',
    'LAST_FORECAST_DATE_ERROR': "Error while fetching last forecast date",
    'SUBMIT_FORECAST': 'Error occurred while submitting forecast data',
    'GET_STOCK_FAILURE': "Couldn't fetch In hand , In Transit, Open Stock data",
    'SIH_SS_CHECK': "Some error occurred while send email to distributors whose stock in hand is lesser than safety stock",
    'GET_STOCK_LEVEL_SYNC_STATUS': "Couldn't fetch stock level sync status",
    'SKU_STOCK_DATA': "Couldn't fetch stock data for the sku",
    'ARS_AUTO_SUBMIT': "Some error occurred while auto submit of orders",
    'AUTOMATED_VALIDATION': "Some error occurred while automated ARS validation",
    'MOQ_MAPPING_DATA': "Some error occurred while fetching MOQ DB mapping data",
    'MOQ_UPDATE': "Some error occurred while updating MOQ(s)",
    'DISTRIBUTOR_MOQ_DATA': "Some error occurred while fetching distributor MOQ data",
    'GET_ALL_ARS_TOLERANCE': "Some error occurred while fetching ARS tolerance data",
    'GET_ARS_TOLERANCE': "ARS tolerance data not found for the area code/customer group combination",
    'UPDATE_ARS_TOLERANCE': "Some error occurred while updating ARS tolerance data",
    'ARS_WINDOW_NOTIFICATION': "Forecast adjustment window notification not sent",
    'UPSERT_SKU_RULE_CONFIGURATIONS': "Some error occurred while saving SKU rule configurations",
    'FETCH_PO_DETAILS': "PO details data not found",
    'FETCH_ORDERS': "Couldn't fetch orders",
    'DISTRIBUTORS_FILE': "Distributors file does not exist!",
    'DISTRIBUTOR_MIGRATION': "Failed to migrate distributors",
    'WAREHOUSE_DETAILS_MIGRATION': "Failed to migrate warehouse details",
    'WAREHOUSE_DETAILS_FILE': "Warehouse details file does not exist!",
    'SALES_HIERARCHY_FILE': "Sales hierarchy file does not exist!",
    'SALES_HIERARCHY_MIGRATION': "Failed to migrate sales hierarchy details, since sales_hierachy table is not empty",
    'MATERIALS_MIGRATION': "Failed to migrate materials",
    'MATERIALS_FILE': "Materials file does not exist!",
    'FETCH_WAREHOUSE_DETAILS': "Failed to fetch warehouse details data",
    'FETCH_RUSH_ORDER_REQUESTS': "Failed to fetch rush order requests",
    'INSERT_ORDER_REQUEST': "Failed to insert order request",
    'SAVE_PROMISED_CREDIT': "Failed to save promised credit",
    'RUSH_ORDER_APPROVAL_COUNT': "Failed to fetch count of rush order requests approved in current month",
    'RUSH_ORDER_SET_EXPIRED': "Failed to set pending rush order requests, crossing expiry window, expired",
    'UPDATE_RUSH_ORDER_REQUEST': "Failed to update rush order request",
    'UPDATE_QUANTITY_NORM': "Failed to update quantity norm",
    'BULK_MOQ_UPDATE': 'Some error occurred while updating MOQ(s)',
    'BULK_DIST_MOQ_FETCH': 'Some error occurred while fetching MOQ(s)',
    'FETCH_ORDER_REQUEST': "Failed to fetch Order request data",
    'EXCEL_UPLOAD_FAILURE': "Failed to upload excel data",
    'FILE_EMPTY': "File is empty",
    'FORECAST_FILE_MISSING_SALES_DATA': "Forecast file is missing sales data columns",
    'FORECAST_FILE_TOTAL_MISMATCH': "Totals at PSKU level do not match",
    'FORECAST_FILE_MISMATCH': "Forecast file has mismatched data at one of the following columns- DB Code, DB Name, PSKU, PSKU Description or Forecast",
    'FORECAST_FILE_NEGATIVE_VALUES': "Adjusted forecast has negative values",
    'FORECAST_FILE_INVALID_VALUES': "Adjusted forecast has invalid numbers or empty values",
    'NOT_INTEGER_VALUES': "Adjusted forecast has decimal values",
    'UPLOAD_FAILURE': "Upload has failed, Please try again later",
    "INVALID_FILE": "Data validation of the uploaded file failed due to the following reasons",
    "EMPTY_FILE": "Uploaded file is empty",
    "SERVICE_ALREADY_RUNNING": "Service Already Running in backend",
    "STOCK_NORM_NOT_DEFINED": "Stock norm is not defined for the month. Please contact your ASM or Admin for the same",
    "STOCK_NORM_DISTRIBUTOR_FETCH_FAILURE": "Failed to get DB filters",
    "FETCH_RO_REASONS": "Failed to fetch Rush Order request reasons",
    'TRIGGER_RO_APPROVAL_EMAIL': "Failed to send Rush Order approval email",
    "NON_FORECASTED_SKU_FETCH": "Failed to fetch non-forecasted PSKUS",
    "NON_FORECASTED_INSERT": 'Failed to insert non forecasted sku',
    "FETCH_DISTRIBUTOR_LIST": "Failed to get db list",
    "NO_MODIFICATION": "No modification in the forecast data",
    "QUANTITY_NORM_SYNC_ERROR": "Failed to sync quantity norm",
    "FORECAST_TOTAL_SYNC": "Failed to sync forecast total",
    "UPSERT_SOQ_NORMS": "Failed to update SOQ norms",
    "FETCH_SOQ_NORMS": "Failed to fetch SOQ norms",
    "FETCH_SOQ_NORMS_DIVISION_LIST": "Failed to fetch SOQ norms division list",
    "DELETE_SOQ_NORM": "Failed to delete SOQ norm",
    'FETCH_TOLERANCE_EXCLUDED_PSKUS': 'Failed to fetch tolerance excluded pskus',
    'FETCH_MATERIALS_LIST': 'Failed to fetch materials list',
    'UPDATE_TOLERANCE_EXCLUDED_PSKUS': 'Failed to update tolerance excluded pskus',
    'SKU_SOQ_NORM_DOWNLOAD': "Failed to download SKU SOQ Norm",
    'DISTRIBUTOR_CENSUS_CUSTOMER_GROUP_DOWNLOAD': "Failed to download Distributor Census Customer Group",
    'DBCensus_UPLOAD_ERROR': 'Error uploading DBCensus Customer Group',
    'SKU_SOQ_NORM_UPLOAD_ERROR': 'Error uploading SkuSoqNorm Customer Group',
    "FORECAST_DOWNLOAD": "Failed to fetch forecast download path",
    "FORECAST_UPLOAD": "Failed to validate the uploaded Forecast File",
    "FORECAST_DATA_UPDATE": "Failed to fetch forecast file from S3 and update forecast data",
    "STOCK_NORM_RANGE": "Stock norm values out of range of 0 to 30 days",
    "STOCK_NORM_INVALID": "Stock Norm should be positive whole number",
    "STOCK_NORM_UPLOAD_ERROR": "Error uploading Stock Norm",
    "STOCK_NORM_CONTAINS_SPECIAL_CHARACTERS": "Stock norm contains alphabets or special characters",
    "FETCH_ARS_CONFIGURATIONS": "Failed to fetch ARS configurations",
    "UPCOMING_PDP_FETCH": "Failed to fetch upcoming PDP",
    'DELETE_FAILURE': 'Failed to delete',
    'SEND_RO_PENDING_REPORT': 'Failed to send pending non-expired rush orders report',
    'PLANT_DETAILS_ERROR': 'Failed to fetch plant details',
};
