export const SuccessMessage = {
    'UPDATE_MATERIAL_TAGS_SUCCESS': 'Material Tags updated successfully',
    'UPSERT_SALES_HIERARCHY_DETAILS_SUCCESS': 'Sales Hierarchy Details upserted successfully',
    'SYNC_LOGS': 'Sync logs fetched successfully',
    'MATERIALS_TAG': 'Materials tags fetched successfully',
    'REMOVE_DRAFT_SUCCESS': 'Your cart has been removed successfully',
    'REMOVE_EXPIRED_CARTS_SUCCESS': 'Expired carts of the distributor have been removed successfully',
    'ZONE_WISE_ORDER_SUCCESS': 'Zone wise orders fetched successfully',
    'CATEGORY_WISE_ISSUES_SUCCESS': 'Category wise reported issues fetched successfully',
    'GET_SDR_LIST_SUCCESS': 'Service delivery request fetched successfully',
    'GET_SDR_REPORT_DATA_SUCCESS': 'SDR Report data fetched successfully',
    'GET_SD_RESPONSE_REPORT_DATA_SUCCESS': 'SD Response Report data fetched successfully',
    'GET_BRAND_VARIANT_LIST': 'Brand variant list fetched successfully',
    'GET_FORECAST': 'Forecast data fetched successfully',
    'GET_REGIONAL_BRAND_LIST': 'Regional brand list fetched successfully',
    'UPDATE_FORECAST': 'Forecast updated successfully',
    'FORECAST_CONFIGURATION_LIST_SUCCESS': 'Forecast configurations fetched successfully',
    'FORECAST_CONFIGURATION_UPDATE_SUCCESS': 'Forecast configuration updated successfully',
    'GET_FORECAST_SUMMARY': 'Forecast summary data fetched successfully',
    'LAST_FORECAST_DATE': "Last forecast date fetched successfully",
    'SUBMIT_FORECAST': 'Forecast data submitted successfully',
    'GET_STOCK_DATA': 'In hand , In Transit, Open Stock data fetched successfully',
    'SIH_SS_CHECK': 'Email sent to distributors whose stock in hand is lesser than safety stock.',
    'ARS_AUTO_SUBMIT': 'ARS auto-submit done successfully',
    'AUTOMATED_VALIDATION': "ARS Automated Validation executed successfully",
    'SKU_STOCK_DATA': "Stock data of the sku is fetched successfully",
    'MOQ_MAPPING_DATA': "MOQ DB mapping data fetched successfully",
    'MOQ_UPDATE': "MOQ(s) updated successfully",
    'DISTRIBUTOR_MOQ_DATA': "Distributor MOQ data fetched successfully",
    'ARS_WINDOW_NOTIFICATION': "Forecast adjustment window notification sent successfully",
    'FETCH_CUSTOMER_GROUPS': "Customer groups fetched successfully",
    'FETCH_SKU_CODE': "SKU code fetched successfully",
    'FETCH_SKU_DETAILS': "SKU details fetched successfully",
    'UPSERT_SKU_RULE_CONFIGURATIONS': "SKU rule configurations saved successfully",
    'FETCH_SKU_RULE_CONFIGURATIONS': "SKU rule configurations fetched successfully",
    'GET_EXCLUDED_MATERIALS': "Excluded materials fetched successfully",
    'FETCH_PO_DETAILS': "PO details fetched successfully",
    'FETCH_ORDERS': "Orders fetched successfully",
    'DISTRIBUTOR_MIGRATION': "Successfully migrated distributors",
    'WAREHOUSE_DETAILS_MIGRATION': "Successfully migrated warehouse details",
    'SALES_HIERARCHY_MIGRATION': "Successfully migrated sales hierarchy details",
    'MATERIALS_MIGRATION': "Successfully migrated materials",
    'FETCH_WAREHOUSE_DETAILS': "Warehouse details data fetched successfully",
    'FETCH_RUSH_ORDER_REQUESTS': "Rush order requests fetched successfully",
    'INSERT_ORDER_REQUEST': "Order request inserted successfully",
    'SAVE_PROMISED_CREDIT': "Promised credit saved successfully",
    'FETCH_BRAND_AND_BRAND_VARIANT_COMBINATIONS': "Brand and brand variant combinations fetched successfully",
    'FETCH_BRAND_VARIANT_DETAILS': "Brand variant details fetched successfully",
    'UPSERT_BRAND_VARIANT_PRIORITIZATION': "Brand variant prioritization saved successfully",
    'FETCH_PRIORITIZATION': "Prioritization fetched successfully",
    'RUSH_ORDER_APPROVAL_COUNT': "Count of rush order requests approved in current month fetched successfully",
    'RUSH_ORDER_SET_EXPIRED': "Pending rush order requests crossing the expiry window are set to expired",
    'UPDATE_RUSH_ORDER_REQUEST': "Rush order request updated successfully",
    'UPDATE_QUANTITY_NORM': "Quantity norm updated successfully",
    'FETCH_AREA_REGION':'Area and region fetched successfully',
    'FETCH_ORDER_REQUEST': "Order request data fetched successfully",
    'UPLOAD_SUCCESSFUL': "Upload Successful",
    "FETCH_STOCK_NORM_DISTRIBUTOR_FILTER_SUCCESS": "DB Filters fetched successfully",
    'FETCH_RO_REASONS' : "Rush Order request reasons fetched successfully",
    'TRIGGER_RO_APPROVAL_EMAIL': "Rush Order approval email sent successfully",
    'SERVICE_RUNNING_IN_BACKGROUND': "Service is running in background...",
    'NON_FORECASTED_SKU_FETCH': 'Successfully fetched non forecasted sku',
    'NON_FORECASTED_INSERT': 'Successfully inserted non forecasted sku',
    "FETCH_DISTRIBUTOR_LIST": "Successfully fetched distributor list",
    "UPSERT_SOQ_NORMS": "Successfully updated SOQ norms",
    "FETCH_SOQ_NORMS": "Successfully fetched SOQ norms",
    "FETCH_SOQ_NORMS_DIVISION_LIST": "Successfully fetched SOQ norms division list",
    "DELETE_SOQ_NORM": "Successfully deleted SOQ norm",
    'FETCH_TOLERANCE_EXCLUDED_PSKUS': 'Successfully fetched tolerance excluded pskus',
    'FETCH_MATERIALS_LIST': 'Materials list fetched successfully',
    'UPDATE_TOLERANCE_EXCLUDED_PSKUS': 'Successfully updated tolerance excluded pskus',
    'SKU_SOQ_NORM_DOWNLOAD': 'SKU SOQ Norm download successful',
    'DISTRIBUTOR_CENSUS_CUSTOMER_GROUP_DOWNLOAD': "Distributor Census Customer Group download successful",
    'DBCensus_UPLOAD_SUCCESS': 'DBCensus Customer Group uploaded successfully',
    'SKU_SOQ_NORM_UPLOAD_SUCCESS': 'SkuSoqNorm Customer Group uploaded successfully',
    "FORECAST_DOWNLOAD": "Forecast file download path fetched successfully",
    "STOCK_NORM_UPLOAD_SUCCESS": "Stock Norm uploaded successfully",
    "UPCOMING_PDP_FETCH": "Upcoming PDP fetched successfully",
    'DELETE_SUCCESS':'Deleted Successfully',
    'SEND_RO_PENDING_REPORT': 'Pending non-expired rush orders report sent successfully',
    'PLANT_DETAILS_SUCCESS': 'Plants details fetched successfully',
};
