export const ErrorMessage = {
    PERMISSION_ISSUE: 'You are not permitted to access this resource',
    GET_CL_APPROVER_FINANCE: 'Failed to fetch Credit Limit Finance Approvers',
    UPLOAD_CREDIT_REQUEST_ERROR: 'Some error occurred while uploading credit request',
    UPLOAD_REQUEST_ERROR: 'Some error occurred while Uploading request file',
    CUSTOMER_GROUP_LIST_ERROR: 'Error in fetching customer groups',
    FETCH_CREDIT_EXTENTION_REQUESTS: 'Error in fetching credit extention requests',
    FETCH_ORDER_REQUEST: 'Failed to fetch Requested Details',
    Email_upload_failed: 'Error in uploading Email',
    SYNC_LOGS_FETCHED_ERROR: 'Some error occurred while fetching sync logs',
    INSERT_CREDIT_EXTENTION_REQUEST: 'Failed to insert credit extention request',
    UPDATE_CREDIT_EXTENSION_REQUEST: 'Error while updating the request by approver',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    USER_MAPPING_LIST_ERROR: 'Error in fetching user mapping list',
    ACCOUNT_LIST_ERROR: 'Error in fetching account masters',
    ROLE_MISMATCH: 'Current Role does not have permission to approve the request',
    ALREADY_RESPONDED: 'You have already responded to this request',
    NOT_RESPONDED_BY_PREVIOUS_APPROVER: 'You are not able to approve/reject until previous approver approves/reject',
    GET_CL_APPROVER_SALES: 'Failed to fetch Credit Limit Sales Approvers',
    INSERT_APPROVER_DETAILS: 'Failed to insert approver details',
    FETCH_APPROVER_DETAILS: 'Failed to fetch approver details',
    FETCH_RISK_CATEGORY: 'Failed to fetch Risk category',
    REVERT_BASE_LIMIT: 'No data Found to revert base limit',
    FETCH_LATEST_RECORDS: 'No latest records found',
    ADD_APPROVER_CONFIG: 'Failed to add approver configuration',
    GET_CATEGORY_LIST: 'Failed to fetch Approver Category',
    FAILED_REVERT_BASE_LIMIT: 'Failed to revert base limit',
    GET_NEW_CUSTOMER_GROUP: 'Failed to fetch unmapped customer group',
    MT_CL_REPORT_ERROR: 'Error in fetching MT Credit Limit Report',
    GET_GT_APPROVERS_ERROR: 'Failed to fetch GT Approvers',
    GET_GT_CLUSTER_ERROR: 'Failed to fetch GT Cluster',
    FETCH_GT_APPROVER_DETAILS: 'Failed to fetch GT Approver details',
    FETCH_GT_REQUESTOR_DETAILS: 'Failed to fetch GT Requestor details',
    FETCH_GT_ADD_REQUESTOR: 'Failed to fetch GT Details to add requestors',
    ADD_GT_REQUESTOR: 'Failed to add GT Requestor',
    GT_CL_REQUESTORS_DATA: 'Error in fetching GT Credit Limit REQUESTOR data',
    NOT_AUTHORIZED: 'You are not authorized to perform this action',
    FETCH_CUSTOMER_GROUP_FOR_SETTINGS: 'Error in fetching customer group for settings',
    GT_START_TRANSACTION_CRON: 'Failed to process GT Start transaction Cron',
    GT_START_NO_DATA: 'No data found for GT Start transaction',
    GT_END_TRANSACTION_CRON: 'Failed to process GT End transaction Cron',
    GT_END_NO_DATA: 'No data found for GT End transaction',
    GT_CL_REPORT_ERROR: 'Error in fetching GT Credit Limit Report',
};