export const SuccessMessage = {
    UPLOAD_CREDIT_REQUEST_SUCCESS: 'Credit request uploaded successfully',
    CUSTOMER_GROUP_LIST_SUCCESS: 'Customer group fetched successfully',
    FETCH_CREDIT_EXTENTION_REQUESTS: 'Credit extention requests fetched successfully',
    FETCH_ORDER_REQUEST: 'Credit Request data fetched successfully',
    INSERT_CREDIT_EXTENTION_REQUEST: 'Credit extention request form submitted successfully',
    GET_CL_APPROVER_FINANCE: 'Credit Limit Finance Approvers fetched successfully',
    UPDATE_CREDIT_EXTENSION_REQUEST: 'Credit extension request updated successfully',
    USER_MAPPING_LIST_SUCCESS: 'User mapping list fetched successfully',
    ACCOUNT_LIST_SUCCESS: 'Account masters fetched successfully',
    RUN_BASE_LIMIT_JOB: 'Base limit job ran successfully',
    GET_CL_APPROVER_SALES: 'Credit Limit Sales Approvers fetched successfully',
    INSERT_APPROVER_DETAILS: 'Approver details updated successfully',
    FETCH_APPROVER_DETAILS: 'MT Approver details fetched successfully',
    FETCH_RISK_CATEGORY: 'Risk category fetched successfully',
    REVERT_BASE_LIMIT: 'Base limit reverted successfully',
    FETCH_LATEST_RECORDS: 'Latest uploaded record fetched successfully',
    ADD_APPROVER_CONFIG: 'Approver configuration added successfully',
    GET_CATEGORY_LIST: 'Approver Category fetched successfully',
    GET_NEW_CUSTOMER_GROUP: 'Unmapped customer group fetched successfully',
    MT_CL_REPORT_SUCCESS: 'MT Credit Limit Report fetched successfully',
    GET_GT_APPROVERS_SUCCESS: 'GT Approvers fetched successfully',
    GET_GT_CLUSTER_SUCCESS: 'GT Cluster fetched successfully',
    FETCH_GT_APPROVER_DETAILS: 'GT Approver details fetched successfully',
    FETCH_GT_REQUESTOR_DETAILS: 'GT Requestor details fetched successfully',
    FETCH_GT_ADD_REQUESTOR: 'GT Details fetched to add requestors',
    ADD_GT_REQUESTOR: 'GT Requestor added successfully',
    GT_CL_REQUESTORs_DATA: 'GT Credit Limit Requestor data fetched successfully',
    FETCH_CUSTOMER_GROUP_FOR_SETTINGS: 'Customer group for settings fetched successfully',
    GT_START_TRANSACTION_CRON: 'GT Start transaction cron job ran successfully',
    GT_END_TRANSACTION_CRON: 'GT End transaction cron job ran successfully',
    GT_CL_REPORT_SUCCESS: 'GT Credit Limit Report fetched successfully',
};
