export const ErrorMessage = {
    ROR_DATA_SYNC_FAILED: 'NO Data available',
    SAP_API_FAILED: 'SAP API failed to give success response',
    PRODUCT_SYNC_FAILED: 'Product Master Data syncing failed',
    DISTRIBUTOR_SYNC_FAILED: 'Distributor Master Data syncing failed',
    OPEN_SO_SYNC_FAILED: 'Open SO Data syncing failed',
    DATA_SYNC_ERROR: 'Some issue occurred while syncing data',
    WAREHOUSE_DETAILS_ERROR: 'Some error occurred while fetching ship to and unloading points',
    GET_SALES_ORDER_DELIVERY_ERROR: 'Some error occurred while fetching sales order delivery',
    GET_SALES_ORDER_INVOICE_ERROR: 'Some error occurred while fetching sales order invoice',
    SO_DETAILS_FETCH_ERROR: 'Some error occurred while fetching so details',
    SALES_HIERARCHY_SYNC_FAILED: 'Some error occurred while syncing sales hierarchy details',
    PERMISSION_ISSUE: 'You are not permitted to access this resource',
    PRODUCT_DISTRIBUTOR_MAPPING_FAILED: 'Some error occurred while mapping products to distributors',
    MATERIALS_BOUM_EXPLODE_ERROR: 'Some error occurred while fetching materials BOM explode',
    PRODUCT_DISTRIBUTOR_MAPPING_FILE_ERROR: 'Some error occurred while reading file from S3 bucket',
    REQUEST_CATEGORY_FETCH_ERROR: 'Some error occurred while fetching service request categories',
    REQUEST_CATEGORY_CREATE_ERROR: 'Some error occurred while adding service request category',
    REQUEST_CATEGORY_UPDATE_ERROR: 'Some error occurred while modifying service request category',
    ENABLE_PDP_RESTRICTION_NOT_FOUND: 'ENABLE_PDP_RESTRICTION key not found in app level settings.',
    DISTRIBUTOR_NOT_FOUND: 'Distributor with provided id not found.',
    INVALID_DAY_TO_PLACE_ORDER: 'You are allowed to place an order as per your PDP Day only.',
    PARTNER_MISMATCH_ERROR_CODE: 'ERR-DBO-OSBT-006-PARTNER_MISMATCH',
    USER_CREATE_ERROR: 'Some error occurred while adding users.',
    MAPPING_REQUEST_CREATE_ERROR: 'Some error occurred while adding mapping request',
    GET_MAPPING_REQUEST_LIST_ERROR: 'Some error occurred while fetching mapping request',
    UPDATE_MAPPING_REQUEST_FAILED: 'Some error occurred while updating mapping request',
    PLANT_CODE_NOT_FOUND: 'Plant code not found',
    GET_TSE_LIST_ERROR: 'Tse list not found',
    MOBILE_NOT_UPDATED: 'Mobile updation failed, Please contact admin',
    EMAIL_NOT_UPDATED: 'Email updation failed, Please contact admin',
    EMAIL_ID_ALREADY_EXIST: 'Email Id already exist',
    INVALID_OTP: 'Invalid otp',
    INVALID_LINK: 'Invalid link',
    INVALID_REQUEST: 'Invalid Request',
    PLANT_REQUEST_CREATE_ERROR: 'Some error occurred while fetching plant request',
    PDP_UPDATE_REQUEST_FAILURE: "Couldn't save PDP update request",
    PDP_UPDATE_REQUESTS_FETCH_FAILURE: "Couldn't fetch PDP update request list",
    PDP_UPDATE_RESPONSE_FAILURE: "Couldn't update PDP",
    CUSTOMER_GROUP_DETAILS_FAILURE: "Couldn't fetch Customer group details",

    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    CREDIT_CRUNCH_NOTIFICATION: 'Failed to send credit crunch notification ',
    NEW_PSKU_FAILED: 'Failed to create Data',
    PSKU_UPDATE_FAILED: 'Failed to update Data',
    MRP_AND_CASELOT_CHECK_FAILURE: 'Failed to fetch MRP and caselot check details',
    SALES_ORDER_CREATION_FAILED: 'Failed to create sales order',
    MRP2_CHECK_FAILURE: 'Failed to fetch MRP2 check details',
    INVALID_FILE_FORMAT: 'Please upload the file with columns in the following sequence: Year, State Code, State Description, Holiday Date.',
    SERVICE_ALREADY_RUNNING: 'Service Already Running in backend',
    RUSH_ORDER_SET_EXPIRED: 'Failed to set pending rush order requests, crossing expiry window, expired',
    SIH_SS_CHECK: 'Some error occurred while send email to distributors whose stock in hand is lesser than safety stock',
    MULE_API_FAILED: 'Mule API failed to give success response',
    MT_ECOM_SO_SYNC_FAILED: 'MT Ecom SO Sync Failed',
    PREVIOUS_PROCESS_CALENDER: 'Records already Inserted',
    NOURISHCO_FORECAST_FILE_DOWNLOAD_FAILED: 'Some error occurred while downloading nourishco forecast file',
    DELIVERY_CODE_REPORT_FAILED: 'Some error occurred while fetching delivery code reports',
};
