import { roles } from './roles';
import LocalAuth from '../util/middleware/auth.js';
import _ from 'lodash';

export const pages = {
    DASHBOARD: 'DASHBOARD',
    REQUEST: 'REQUEST',
    FORECAST: 'FORECAST',
    MOQ: 'MOQ',
    REPORT_ISSUE: 'REPORT_ISSUE',
    HELP: 'HELP',
    SKU_DATA: 'SKU_DATA',
    MT_ECOM: 'MT_ECOM',
    ORDER: 'ORDER',
    MT_ECOM_KAMS_MAPPING: 'MT_ECOM_KAMS_MAPPING',
    SHOPIFY: 'SHOPIFY',
    CREDIT_LIMIT: 'CREDIT_LIMIT',
};

export const features = {
    ADMIN_VIEW: 'ADMIN_VIEW',
    LOGISTICS_VIEW: 'LOGISTICS_VIEW',
    VIEW_CUSTOMER_GROUP_FILTER: 'VIEW_CUSTOMER_GROUP_FILTER',
    VIEW_REGION_FILTER: 'VIEW_REGION_FILTER',
    VIEW_STATE_FILTER: 'VIEW_STATE_FILTER',
    VIEW_AREA_CODE_FILTER: 'VIEW_AREA_CODE_FILTER',
    VIEW_REGION: 'VIEW_REGION',
    VIEW_MASS_EDIT: 'VIEW_MASS_EDIT',
    EDIT_PDP: 'EDIT_PDP',
    EDIT_ARS: 'EDIT_ARS',
    EDIT_REGULAR: 'EDIT_REGULAR',
    EDIT_LOGIN: 'EDIT_LOGIN',
    EDIT_PO_SO_EMAIL: 'EDIT_PO_SO_EMAIL',
    EDIT_PO_SO_SMS: 'EDIT_PO_SO_SMS',
    EDIT_INVOICE_EMAIL: 'EDIT_INVOICE_EMAIL',
    EDIT_INVOICE_SMS: 'EDIT_INVOICE_SMS',
    EDIT_TSE_EMAIL: 'EDIT_TSE_EMAIL',
    EDIT_TSE_SMS: 'EDIT_TSE_SMS',
    EDIT_LIQ: 'EDIT_LIQ',
    EDIT_DB_FLAGS: 'EDIT_DB_FLAGS',
    VIEW_RESERVED_CREDIT: 'VIEW_RESERVED_CREDIT',
    EDIT_RESERVED_CREDIT: 'EDIT_RESERVED_CREDIT',
    CREATE_ORDER: 'CREATE_ORDER',
    EDIT_RO: 'EDIT_RO',
    EDIT_BO: 'EDIT_BO',
    EDIT_NOC: 'EDIT_NOC',
    VIEW_PLANT_FILTER: 'VIEW_PLANT_FILTER',
    LOCK_PDP: 'LOCK_PDP',
    PDP_LOCK_BYEPASS: 'PDP_LOCK_BYEPASS',
    REGULAR_ORDER: 'REGULAR_ORDER',
    BULK_ORDER: 'BULK_ORDER',
    LIQUIDATION: 'LIQUIDATION',
    AUTO_ORDER: 'AUTO_ORDER',
    SELF_LIFTING: 'SELF_LIFTING',
    RUSH_ORDER: 'RUSH_ORDER',
    CCO_SPECIAL_ORDER: 'CCO_SPECIAL_ORDER',
    SHOW_STATUS: 'SHOW_STATUS',
    NO_ACTIONS: 'NO_ACTIONS',
    MT_ECOM_KAMS_MAPPING: 'MT_ECOM_KAMS_MAPPING',
    EDIT_AOS: 'EDIT_AOS',
    DELETE_BUTTON: 'DELETE_BUTTON',
    SHOW_RE_TRIGGER: 'SHOW_RE_TRIGGER',
    SHOW_BUTTON_RESEND_PO: 'SHOW_BUTTON_RESEND_PO',
    DISABLE_SUBMIT: 'DISABLE_SUBMIT',
    MULTIPLE_SESSIONS: 'MULTIPLE_SESSIONS',
    DUPLICATE_TAB: 'DUPLICATE_TAB',
    CREDIT_LIMIT: 'CREDIT_LIMIT',
    EDIT_APPROVAL_CL: 'EDIT_APPROVAL_CL',
    CREATE_REQUEST_CL: 'CREATE_REQUEST_CL',
    REMARKS_VIEW: 'REMARKS_VIEW',
    ACCOUNT_VIEW: 'ACCOUNT_VIEW',
    APPROVER_CONFIG: 'APPROVER_CONFIG',
    SUBMIT_REQUEST: 'SUBMIT_REQUEST',
    EDIT_APPROVER_CONFIG: 'EDIT_APPROVER_CONFIG',
    ACCOUNT_EDIT: 'ACCOUNT_EDIT',
    EDIT_DELIVERY_CODE_EMAIL: 'EDIT_DELIVERY_CODE_EMAIL',
    EDIT_DELIVERY_CODE_SMS: 'EDIT_DELIVERY_CODE_SMS',
    TRANSACTIONS_VIEW: 'TRANSACTIONS_VIEW',
    GT_REPORTS_SECTION: 'GT_REPORTS_SECTION',
    MT_REQUEST_CHANNEL: 'MT_REQUEST_CHANNEL',
    GT_REQUEST_CHANNEL: 'GT_REQUEST_CHANNEL',
    CL_SECONDARY_REMARKS_VIEW: 'CL_SECONDARY_REMARKS_VIEW',
    EDIT_GT_CONFIG: 'EDIT_GT_CONFIG',
    VIEW_GT_CONFIG: 'VIEW_GT_CONFIG',
    CL_AGEING_REPORT: 'CL_AGEING_REPORT',
    GT_UPLOAD_ON_REQUEST: 'GT_UPLOAD_ON_REQUEST',
    GT_APPROVE_REQUEST: 'GT_APPROVE_REQUEST',
};

const distributorNav = {
    DASHBOARD: {
        VIEW: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.TSE,
            roles.ASM,
            roles.DIST_ADMIN,
            roles.RSM,
            roles.OPERATIONS,
            roles.CLUSTER_MANAGER,
            roles.CALL_CENTRE_OPERATIONS,
            roles.CUSTOMER_SERVICE,
        ],
        VIEW_CUSTOMER_GROUP_FILTER: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.TSE,
            roles.ASM,
            roles.RSM,
            roles.DIST_ADMIN,
            roles.CLUSTER_MANAGER,
            roles.CALL_CENTRE_OPERATIONS,
            roles.CUSTOMER_SERVICE,
        ],
        VIEW_REGION_FILTER: [roles.SUPER_ADMIN, roles.SUPPORT, roles.PORTAL_OPERATIONS, roles.CALL_CENTRE_OPERATIONS, roles.CLUSTER_MANAGER, roles.CUSTOMER_SERVICE],
        VIEW_STATE_FILTER: [roles.SUPER_ADMIN, roles.SUPPORT, roles.PORTAL_OPERATIONS, roles.CLUSTER_MANAGER, roles.CALL_CENTRE_OPERATIONS, roles.CUSTOMER_SERVICE],
        VIEW_AREA_CODE_FILTER: [roles.SUPER_ADMIN, roles.SUPPORT, roles.PORTAL_OPERATIONS, roles.RSM, roles.CLUSTER_MANAGER, roles.CALL_CENTRE_OPERATIONS, roles.CUSTOMER_SERVICE],
        VIEW_REGION: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.RSM,
            roles.DIST_ADMIN,
            roles.OPERATIONS,
            roles.CLUSTER_MANAGER,
            roles.CALL_CENTRE_OPERATIONS,
            roles.CUSTOMER_SERVICE,
        ],
        VIEW_MASS_EDIT: [roles.SUPER_ADMIN, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER],
        EDIT_LIQ: [roles.SUPER_ADMIN, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER],
        EDIT_PDP: [roles.SUPER_ADMIN, roles.TSE, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER, roles.CUSTOMER_SERVICE],
        EDIT_ARS: [roles.SUPER_ADMIN],
        EDIT_REGULAR: [roles.SUPER_ADMIN],
        EDIT_LOGIN: [roles.SUPER_ADMIN],
        EDIT_PO_SO_EMAIL: [roles.SUPER_ADMIN, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER],
        EDIT_PO_SO_SMS: [roles.SUPER_ADMIN, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER],
        EDIT_INVOICE_EMAIL: [roles.SUPER_ADMIN, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER],
        EDIT_INVOICE_SMS: [roles.SUPER_ADMIN, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER],
        EDIT_TSE_EMAIL: [roles.SUPER_ADMIN, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER],
        EDIT_TSE_SMS: [roles.SUPER_ADMIN, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER],
        EDIT_DB_FLAGS: [roles.SUPER_ADMIN, roles.TSE, roles.ASM, roles.RSM, roles.DIST_ADMIN, roles.CLUSTER_MANAGER],
        VIEW_RESERVED_CREDIT: [roles.SUPER_ADMIN, roles.SUPPORT, roles.TSE, 'DISTRIBUTOR'],
        EDIT_RESERVED_CREDIT: [roles.SUPER_ADMIN, roles.TSE, 'DISTRIBUTOR'],
        CREATE_ORDER: [roles.SUPER_ADMIN, roles.CLUSTER_MANAGER, roles.DIST_ADMIN, roles.RSM, roles.OPERATIONS, roles.ASM, roles.TSE, 'DISTRIBUTOR', roles.CALL_CENTRE_OPERATIONS],
        EDIT_RO: [roles.SUPER_ADMIN],
        EDIT_BO: [roles.SUPER_ADMIN],
        EDIT_NOC: [roles.SUPER_ADMIN],
        VIEW_PLANT_FILTER: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.TSE,
            roles.ASM,
            roles.RSM,
            roles.CLUSTER_MANAGER,
            roles.CALL_CENTRE_OPERATIONS,
            roles.CUSTOMER_SERVICE,
        ],
        LOCK_PDP: [roles.SUPER_ADMIN],
        PDP_LOCK_BYEPASS: [roles.SUPER_ADMIN, roles.CUSTOMER_SERVICE],
        SHOW_STATUS: [roles.SUPER_ADMIN, roles.SUPPORT, roles.PORTAL_OPERATIONS, roles.OPERATIONS, roles.CLUSTER_MANAGER, roles.ASM, roles.TSE, roles.RSM],
        NO_ACTIONS: [roles.CALL_CENTRE_OPERATIONS],
        EDIT_AOS: [roles.SUPER_ADMIN],
        MULTIPLE_SESSIONS: [roles.SUPER_ADMIN, roles.SUPPORT, roles.VP],
        DUPLICATE_TAB: [roles.SUPER_ADMIN, roles.SUPPORT, roles.VP],
        EDIT_DELIVERY_CODE_EMAIL: [roles.SUPER_ADMIN],
        EDIT_DELIVERY_CODE_SMS: [roles.SUPER_ADMIN],
    },
    REQUEST: {
        VIEW: [
            roles.TSE,
            roles.DIST_ADMIN,
            roles.RSM,
            roles.ASM,
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.CFA,
            roles.LOGISTICS_OFFICER,
            roles.ZONAL_OFFICER,
            roles.CLUSTER_MANAGER,
            roles.VP,
            roles.CUSTOMER_SERVICE,
        ],
    },
    FORECAST: {
        VIEW: [roles.SUPER_ADMIN, roles.SUPPORT, roles.PORTAL_OPERATIONS, roles.ASM, roles.DIST_ADMIN, roles.RSM, roles.CLUSTER_MANAGER, roles.SHOPPER_MARKETING],
    },
    MOQ: {
        VIEW: [roles.SUPER_ADMIN, roles.SUPPORT, roles.PORTAL_OPERATIONS, roles.CFA, roles.LOGISTICS_OFFICER, roles.ZONAL_OFFICER],
    },
    HELP: {
        ADMIN_VIEW: [roles.SUPER_ADMIN, roles.SUPPORT, roles.PORTAL_OPERATIONS],
    },
    REPORT_ISSUE: {
        LOGISTICS_VIEW: [roles.CFA, roles.LOGISTICS_OFFICER, roles.ZONAL_OFFICER],
    },
    SKU_DATA: {
        VIEW: [roles.SUPER_ADMIN, roles.SUPPORT, roles.PORTAL_OPERATIONS, roles.MDM, roles.KAMS, roles.NKAMS],
    },
    MT_ECOM: {
        VIEW: [roles.SUPER_ADMIN, roles.SUPPORT, roles.MDM, roles.KAMS, roles.NKAMS],
    },
    MT_ECOM_KAMS_MAPPING: {
        VIEW: [roles.SUPER_ADMIN, roles.SUPPORT, roles.MDM, roles.NKAMS],
        EDIT: [roles.SUPER_ADMIN, roles.MDM, roles.KAMS, roles.NKAMS],
    },
    ORDER: {
        REGULAR_ORDER: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.TSE,
            roles.ASM,
            roles.DIST_ADMIN,
            roles.RSM,
            roles.OPERATIONS,
            'DISTRIBUTOR',
            roles.CLUSTER_MANAGER,
            roles.CALL_CENTRE_OPERATIONS,
        ],
        BULK_ORDER: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.TSE,
            roles.ASM,
            roles.DIST_ADMIN,
            roles.RSM,
            roles.OPERATIONS,
            'DISTRIBUTOR',
            roles.CLUSTER_MANAGER,
        ],
        LIQUIDATION: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.TSE,
            roles.ASM,
            roles.DIST_ADMIN,
            roles.RSM,
            roles.OPERATIONS,
            'DISTRIBUTOR',
            roles.CLUSTER_MANAGER,
        ],
        AUTO_ORDER: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.TSE,
            roles.ASM,
            roles.DIST_ADMIN,
            roles.RSM,
            roles.OPERATIONS,
            'DISTRIBUTOR',
            roles.CLUSTER_MANAGER,
        ],
        SELF_LIFTING: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.TSE,
            roles.ASM,
            roles.DIST_ADMIN,
            roles.RSM,
            roles.OPERATIONS,
            'DISTRIBUTOR',
            roles.CLUSTER_MANAGER,
        ],
        RUSH_ORDER: [
            roles.SUPER_ADMIN,
            roles.SUPPORT,
            roles.PORTAL_OPERATIONS,
            roles.TSE,
            roles.ASM,
            roles.DIST_ADMIN,
            roles.RSM,
            roles.OPERATIONS,
            'DISTRIBUTOR',
            roles.CLUSTER_MANAGER,
        ],
        CCO_SPECIAL_ORDER: [roles.CALL_CENTRE_OPERATIONS],
        DUPLICATE_TAB: [roles.SUPER_ADMIN, roles.SUPPORT, roles.VP],
    },
    SHOPIFY: {
        VIEW: [roles.SUPER_ADMIN, roles.SUPPORT, roles.PORTAL_OPERATIONS, roles.SHOPIFY_UK, roles.SHOPIFY_OBSERVER, roles.SHOPIFY_SUPPORT],
        SHOW_RE_TRIGGER: [roles.SHOPIFY_UK, roles.SHOPIFY_SUPPORT, roles.SUPER_ADMIN],
        SHOW_BUTTON_RESEND_PO: [roles.SHOPIFY_SUPPORT, roles.SUPER_ADMIN, roles.SHOPIFY_UK, roles.SHOPIFY_OBSERVER],
        DISABLE_SUBMIT: [roles.SHOPIFY_OBSERVER],
        DELETE_BUTTON: [roles.SUPER_ADMIN, roles.SHOPIFY_SUPPORT],
    },
    CREDIT_LIMIT: {
        VIEW: [roles.CL_PRIMARY_APPROVER, roles.CL_SECONDARY_APPROVER, roles.KAMS, roles.NKAMS, roles.RCM, roles.HOF, roles.GT_PRIMARY_APPROVER, roles.GT_SECONDARY_APPROVER],
        CREATE_REQUEST_CL: [roles.KAMS, roles.NKAMS, roles.SUPER_ADMIN, roles.SUPPORT, roles.RCM, roles.HOF],
        EDIT_APPROVAL_CL: [roles.CL_PRIMARY_APPROVER, roles.CL_SECONDARY_APPROVER],
        REMARKS_VIEW: [roles.CL_PRIMARY_APPROVER],
        APPROVER_CONFIG: [roles.CL_PRIMARY_APPROVER, roles.SUPER_ADMIN, roles.SUPPORT],
        EDIT_APPROVER_CONFIG: [roles.CL_PRIMARY_APPROVER, roles.SUPER_ADMIN],
        EDIT_GT_CONFIG: [roles.SUPER_ADMIN, roles.HOF],
        VIEW_GT_CONFIG: [roles.SUPER_ADMIN, roles.SUPPORT, roles.HOF, roles.RCM],
        ACCOUNT_VIEW: [roles.CL_PRIMARY_APPROVER, roles.SUPER_ADMIN, roles.SUPPORT, roles.CL_SECONDARY_APPROVER],
        TRANSACTIONS_VIEW: [roles.CL_PRIMARY_APPROVER, roles.SUPER_ADMIN, roles.SUPPORT, roles.CL_SECONDARY_APPROVER, roles.KAMS, roles.NKAMS],
        ACCOUNT_EDIT: [roles.CL_PRIMARY_APPROVER, roles.SUPER_ADMIN],
        SUBMIT_REQUEST: [roles.KAMS, roles.NKAMS],
        CL_SECONDARY_REMARKS_VIEW: [roles.CL_SECONDARY_APPROVER],
        CL_AGEING_REPORT: [roles.CL_PRIMARY_APPROVER, roles.SUPER_ADMIN, roles.SUPPORT],
        GT_REPORTS_SECTION: [roles.SUPER_ADMIN, roles.SUPPORT, roles.RCM, roles.HOF, roles.GT_PRIMARY_APPROVER, roles.GT_SECONDARY_APPROVER],
        MT_REQUEST_CHANNEL: [roles.SUPER_ADMIN, roles.SUPPORT, roles.KAMS, roles.NKAMS, roles.CL_PRIMARY_APPROVER, roles.CL_SECONDARY_APPROVER],
        GT_REQUEST_CHANNEL: [roles.SUPER_ADMIN, roles.SUPPORT, roles.RCM, roles.HOF, roles.GT_PRIMARY_APPROVER, roles.GT_SECONDARY_APPROVER],
        GT_UPLOAD_ON_REQUEST: [roles.RCM, roles.HOF],
        GT_APPROVE_REQUEST: [roles.GT_PRIMARY_APPROVER, roles.GT_SECONDARY_APPROVER],
    },
};

export default distributorNav;

export const hasViewPermission = (page, feature = 'VIEW') => {
    const role = LocalAuth.getAdminRole();
    return !!_.intersection(distributorNav[page][feature], role).length;
};

export const hasEditPermission = (page, feature = 'EDIT') => {
    const role = LocalAuth.getAdminRole();
    return !!_.intersection(distributorNav[page][feature], role).length;
};

export const hasFeaturePermission = (page, feature) => {
    /**
     * This function explicitly checks for the user role(both SSO and DB) and returns the boolean value
     */
    let userRole = LocalAuth.getRole() ? LocalAuth.getAdminRole() : LocalAuth.getDistributorRole();
    if (typeof userRole === 'string') {
        userRole = [userRole];
    }
    return !!_.intersection(distributorNav[page][feature], userRole).length;
};
