export const ErrorMessage = {
    FETCH_ERROR: 'Error occurred while fetching data',
    PERMISSION_ISSUE: 'You are not permitted to access this resource',
    BRAND_VARIANT_LIST_ERROR: 'Error occurred while fetching brand variant list',
    GET_FORECAST_ERROR: 'Error occurred while fetching forecast data',
    REGIONAL_BRAND_LIST_ERROR: 'Error occurred while fetching regional brand list',
    UPDATE_FORECAST: 'Error occurred while updating forecast data',
    FORECAST_CONFIGURATIONS_LIST_ERROR: 'Error in fetching forecast configurations list',
    FORECAST_CONFIGURATION_UPDATE_ERROR: 'Error in updating the forecast configuration',
    GET_FORECAST_SUMMARY_ERROR: 'Error occurred while fetching forecast summary data',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    UPSERT_FORECAST_DISTRIBUTION_ERROR: 'Error occurred during upsert of forecast distribution. Please contact Administrator',
    VALIDATION_ERRORS: 'Error in validating # field',
    SUGGESTED_MATERIAL_FETCH_ERROR: 'No recommendations available for Auto-Order. Please place Regular-Order',
    LAST_FORECAST_DATE_ERROR: 'Error while fetching last forecast date',
    SUBMIT_FORECAST: 'Error occurred while submitting forecast data',
    GET_STOCK_FAILURE: "Couldn't fetch In hand , In Transit, Open Stock data",
    SIH_SS_CHECK: 'Some error occurred while send email to distributors whose stock in hand is lesser than safety stock',
    GET_STOCK_LEVEL_SYNC_STATUS: "Couldn't fetch stock level sync status",
    SKU_STOCK_DATA: "Couldn't fetch stock data for the sku",
    ARS_AUTO_SUBMIT: 'Some error occurred while auto submit of orders',
    AUTOMATED_VALIDATION: 'Some error occurred while automated ARS validation',
    MOQ_MAPPING_DATA: 'Some error occurred while fetching MOQ DB mapping data',
    MOQ_UPDATE: 'Some error occurred while updating MOQ(s)',
    DISTRIBUTOR_MOQ_DATA: 'Some error occurred while fetching distributor MOQ data',
    GET_ALL_ARS_TOLERANCE: 'Some error occurred while fetching ARS tolerance data',
    GET_ARS_TOLERANCE: 'ARS tolerance data not found for the area code/customer group combination',
    UPDATE_ARS_TOLERANCE: 'Some error occurred while updating ARS tolerance data',
    ARS_WINDOW_NOTIFICATION: 'Forecast adjustment window notification not sent',
    UPDATE_QUANTITY_NORM: 'Failed to update quantity norm',
    EXCEL_UPLOAD_FAILURE: 'Failed to upload excel data',
    FILE_EMPTY: 'File is empty',
    FORECAST_FILE_MISSING_SALES_DATA: 'Forecast file is missing sales data columns',
    FORECAST_FILE_TOTAL_MISMATCH: 'Totals at PSKU level do not match',
    FORECAST_FILE_MISMATCH: 'Forecast file has mismatched data at one of the following columns- DB Code, DB Name, PSKU, or Forecast',
    FORECAST_FILE_NEGATIVE_VALUES: 'Adjusted forecast has negative values',
    FORECAST_FILE_INVALID_VALUES: 'Adjusted forecast has invalid numbers or empty values',
    NOT_INTEGER_VALUES: 'Adjusted forecast has decimal values',
    UPLOAD_FAILURE: 'Upload has failed, Please try again later',
    INVALID_FILE: 'Data validation of the uploaded file failed due to the following reasons',
    EMPTY_FILE: 'Uploaded file is empty',
    SERVICE_ALREADY_RUNNING: 'Service Already Running in backend',
    STOCK_NORM_NOT_DEFINED: 'Stock norm is not defined for the month. Please contact your ASM or Admin for the same',
    STOCK_NORM_DISTRIBUTOR_FETCH_FAILURE: 'Failed to get DB filters',
    NO_MODIFICATION: 'No modification in the forecast data',
    QUANTITY_NORM_SYNC_ERROR: 'Failed to sync quantity norm',
    FORECAST_TOTAL_SYNC: 'Failed to sync forecast total',
    UPSERT_SOQ_NORMS: 'Failed to update SOQ norms',
    FETCH_SOQ_NORMS: 'Failed to fetch SOQ norms',
    FETCH_SOQ_NORMS_DIVISION_LIST: 'Failed to fetch SOQ norms division list',
    DELETE_SOQ_NORM: 'Failed to delete SOQ norm',
    FETCH_TOLERANCE_EXCLUDED_PSKUS: 'Failed to fetch tolerance excluded pskus',
    FETCH_MATERIALS_LIST: 'Failed to fetch materials list',
    UPDATE_TOLERANCE_EXCLUDED_PSKUS: 'Failed to update tolerance excluded pskus',
    SKU_SOQ_NORM_DOWNLOAD: 'Failed to download SKU SOQ Norm',
    DISTRIBUTOR_CENSUS_CUSTOMER_GROUP_DOWNLOAD: 'Failed to download Distributor Census Customer Group',
    DBCensus_UPLOAD_ERROR: 'Error uploading DBCensus Customer Group',
    SKU_SOQ_NORM_UPLOAD_ERROR: 'Error uploading SkuSoqNorm Customer Group',
    FORECAST_DOWNLOAD: 'Failed to fetch forecast download path',
    FORECAST_UPLOAD: 'Failed to validate the uploaded Forecast File',
    FORECAST_DATA_UPDATE: 'Failed to fetch forecast file from S3 and update forecast data',
    STOCK_NORM_RANGE: 'Stock norm values out of range of 0 to 30 days',
    STOCK_NORM_INVALID: 'Stock Norm should be positive whole number',
    STOCK_NORM_UPLOAD_ERROR: 'Error uploading Stock Norm',
    STOCK_NORM_CONTAINS_SPECIAL_CHARACTERS: 'Stock norm contains alphabets or special characters',
    STOCK_NORM_MANDATORY_COLUMNS: 'Stock norm file should contain mandatory columns - Distributor Code, PSKU, Stock Norm(Days)',
    CLASS_LEVEL_STOCK_NORM_MANDATORY_COLUMNS: 'Class level stock norm file should contain mandatory columns - Distributor Code, A, B, C',
    FETCH_ARS_CONFIGURATIONS: 'Failed to fetch ARS configurations',
    DUPLICATE_DISTRIBUTOR_CODE_PSKU: 'Duplicate distributor code and psku combination',
    DISTRIBUTOR_CODE_PSKU_MAX_MIN_EMPTY: 'Distributor code, psku, max or min cannot be empty',
    MAX_INVALID: 'Max should be positive whole number',
    MIN_INVALID: 'Min should be negative whole number',
    MISSING_MATERIAL_CODE: 'Material code not found in material master',
    MISSING_DISTRIBUTOR_CODE: 'Distributor code not found in distributor master',
    FETCH_PRODUCT_HIERARCHY_FILTER: 'Failed to fetch product hierarchy filter',
    UPSERT_DISTRIBUTOR_PSKU_TOLERANCE: 'Failed to update distributor psku tolerance',
    FETCH_DISTRIBUTOR_PSKU_TOLERANCE: 'Failed to fetch distributor psku tolerance',
    FETCH_FORECAST_DISTRIBUTION: 'Failed to fetch ARS forecast distribution',
    DELETE_DB_PSKU_TOLERANCE: 'Failed to delete DB/PSKU Tolerance',
    STOCK_NORM_AUDIT_DOWNLOAD: 'Failed to download Stock Norm Audit',
    STAGING_TO_ALLOCATION: 'Failed move allocation from staging',
    SHEET_NAME_ERROR_FORECAST_UPLOAD_ASM: 'Sheet name with area code not found or user not an ASM',
    FORECAST_FILE_INVALID_DB_PSKU: 'Forecast file has invalid data at one of the following columns- DB Code,PSKU',
    FETCH_STOCK_NORM_FOR_DISTRIBUTOR: 'Error fetching Stock Norm for distributor',
    FETCH_FORECAST_DUMP_DETAILS: 'Error fetching forecast dump details',
};
