export const SuccessMessage = {
    FETCH_SUCCESS: 'Data fetched successfully',
    SYNC_LOGS: 'Sync logs fetched successfully',
    GET_BRAND_VARIANT_LIST: 'Brand variant list fetched successfully',
    GET_FORECAST: 'Forecast data fetched successfully',
    GET_REGIONAL_BRAND_LIST: 'Regional brand list fetched successfully',
    UPDATE_FORECAST: 'Forecast updated successfully',
    FORECAST_CONFIGURATION_LIST_SUCCESS: 'Forecast configurations fetched successfully',
    FORECAST_CONFIGURATION_UPDATE_SUCCESS: 'Forecast configuration updated successfully',
    GET_FORECAST_SUMMARY: 'Forecast summary data fetched successfully',
    LAST_FORECAST_DATE: 'Last forecast date fetched successfully',
    SUBMIT_FORECAST: 'Forecast data submitted successfully',
    GET_STOCK_DATA: 'In hand , In Transit, Open Stock data fetched successfully',
    SIH_SS_CHECK: 'Email sent to distributors whose stock in hand is lesser than safety stock.',
    ARS_AUTO_SUBMIT: 'ARS auto-submit done successfully',
    AUTOMATED_VALIDATION: 'ARS Automated Validation executed successfully',
    SKU_STOCK_DATA: 'Stock data of the sku is fetched successfully',
    MOQ_MAPPING_DATA: 'MOQ DB mapping data fetched successfully',
    MOQ_UPDATE: 'MOQ(s) updated successfully',
    DISTRIBUTOR_MOQ_DATA: 'Distributor MOQ data fetched successfully',
    ARS_WINDOW_NOTIFICATION: 'Forecast adjustment window notification sent successfully',
    GET_EXCLUDED_MATERIALS: 'Excluded materials fetched successfully',
    UPDATE_QUANTITY_NORM: 'Quantity norm updated successfully',
    UPLOAD_SUCCESSFUL: 'Upload Successful',
    FETCH_STOCK_NORM_DISTRIBUTOR_FILTER_SUCCESS: 'DB Filters fetched successfully',
    SERVICE_RUNNING_IN_BACKGROUND: 'Service is running in background...',
    UPSERT_SOQ_NORMS: 'Successfully updated SOQ norms',
    FETCH_SOQ_NORMS: 'Successfully fetched SOQ norms',
    FETCH_SOQ_NORMS_DIVISION_LIST: 'Successfully fetched SOQ norms division list',
    DELETE_SOQ_NORM: 'Successfully deleted SOQ norm',
    FETCH_TOLERANCE_EXCLUDED_PSKUS: 'Successfully fetched tolerance excluded pskus',
    FETCH_MATERIALS_LIST: 'Materials list fetched successfully',
    UPDATE_TOLERANCE_EXCLUDED_PSKUS: 'Successfully updated tolerance excluded pskus',
    SKU_SOQ_NORM_DOWNLOAD: 'SKU SOQ Norm download successful',
    DISTRIBUTOR_CENSUS_CUSTOMER_GROUP_DOWNLOAD: 'Distributor Census Customer Group download successful',
    DBCensus_UPLOAD_SUCCESS: 'DBCensus Customer Group uploaded successfully',
    SKU_SOQ_NORM_UPLOAD_SUCCESS: 'SkuSoqNorm Customer Group uploaded successfully',
    FORECAST_DOWNLOAD: 'Forecast file download path fetched successfully',
    STOCK_NORM_UPLOAD_SUCCESS: 'Stock Norm uploaded successfully',
    FETCH_ARS_CONFIGURATIONS: 'ARS configurations fetched successfully',
    UPDATE_ARS_CONFIGURATIONS: 'ARS configurations updated successfully',
    FETCH_FORECAST_DISTRIBUTION: 'ARS forecast distribution fetched successfully',
    DB_PSKU_TOLERANCE_UPLOAD_SUCCESS: 'DB PSKU Tolerance uploaded successfully',
    FETCH_PRODUCT_HIERARCHY_FILTER: 'Product Hierarchy Filter fetched successfully',
    UPSERT_DISTRIBUTOR_PSKU_TOLERANCE: 'Distributor PSKU Tolerance updated successfully',
    FETCH_DISTRIBUTOR_PSKU_TOLERANCE: 'Distributor PSKU Tolerance fetched successfully',
    STOCK_NORM_AUDIT_DOWNLOAD: 'Stock Norm Audit download successful',
    ARCHIVE_SYNC_SUCCESS: 'ARS Archive Sync Success',
    FETCH_STOCK_NORM_FOR_DISTRIBUTOR: 'Successfully fetched Stock Norm',
    FETCH_FORECAST_DUMP_DETAILS: 'Successfully fetched forecast dump details',
};
