export const ErrorMessage = {
    SAP_API_FAILED: 'SAP API failed to give success response',
    PRODUCT_SYNC_FAILED: 'Product Master Data syncing failed',
    DISTRIBUTOR_SYNC_FAILED: 'Distributor Master Data syncing failed',
    OPEN_SO_SYNC_FAILED: 'Open SO Data syncing failed',
    DATA_SYNC_ERROR: 'Some issue occurred while syncing data',
    WAREHOUSE_DETAILS_ERROR: 'Some error occurred while fetching ship to and unloading points',
    GET_SALES_ORDER_DELIVERY_ERROR: 'Some error occurred while fetching sales order delivery',
    GET_SALES_ORDER_INVOICE_ERROR: 'Some error occurred while fetching sales order invoice',
    SO_DETAILS_FETCH_ERROR: 'Some error occurred while fetching so details',
    SALES_HIERARCHY_SYNC_FAILED: 'Some error occurred while syncing sales hierarchy details',
    PERMISSION_ISSUE: 'You are not permitted to access this resource',
    PRODUCT_DISTRIBUTOR_MAPPING_FAILED: 'Some error occurred while mapping products to distributors',
    MATERIALS_BOUM_EXPLODE_ERROR: 'Some error occurred while fetching materials BOM explode',
    PRODUCT_DISTRIBUTOR_MAPPING_FILE_ERROR: 'Some error occurred while reading file from S3 bucket',
    REQUEST_CATEGORY_FETCH_ERROR: 'Some error occurred while fetching service request categories',
    REQUEST_CATEGORY_CREATE_ERROR: 'Some error occurred while adding service request category',
    REQUEST_CATEGORY_UPDATE_ERROR: 'Some error occurred while modifying service request category',
    ENABLE_PDP_RESTRICTION_NOT_FOUND: 'ENABLE_PDP_RESTRICTION key not found in app level settings.',
    DISTRIBUTOR_NOT_FOUND: 'Distributor with provided id not found.',
    INVALID_DAY_TO_PLACE_ORDER: 'You are allowed to place an order as per your PDP Day only.',
    PARTNER_MISMATCH_ERROR_CODE: 'ERR-DBO-OSBT-006-PARTNER_MISMATCH',
    USER_CREATE_ERROR: 'Some error occurred while adding users.',
    MAPPING_REQUEST_CREATE_ERROR: 'Some error occurred while adding mapping request',
    GET_MAPPING_REQUEST_LIST_ERROR: 'Some error occurred while fetching mapping request',
    UPDATE_MAPPING_REQUEST_FAILED: 'Some error occurred while updating mapping request',
    PLANT_CODE_NOT_FOUND: 'Plant code not found',
    GET_TSE_LIST_ERROR: 'Tse list not found',
    MOBILE_NOT_UPDATED: 'Mobile updation failed, Please contact admin',
    EMAIL_NOT_UPDATED: 'Email updation failed, Please contact admin',
    EMAIL_ID_ALREADY_EXIST: 'Email Id already exist',
    INVALID_OTP: 'Invalid otp',
    INVALID_LINK: 'Invalid link',
    INVALID_REQUEST: 'Invalid Request',
    PLANT_REQUEST_CREATE_ERROR: 'Some error occurred while fetching plant request',
    PDP_UPDATE_REQUEST_FAILURE: "Couldn't save PDP update request",
    PDP_UPDATE_REQUESTS_FETCH_FAILURE: "Couldn't fetch PDP update request list",
    PDP_UPDATE_RESPONSE_FAILURE: "Couldn't update PDP",
    CUSTOMER_GROUP_DETAILS_FAILURE: "Couldn't fetch Customer group details",
    MDM_DATA_FETCH_FAILED: 'No Data available',
    MDM_DATA_ERROR: 'Some error occurred while fetching MDM data',
    MDM_DATA_SAVE_FAILED: 'Some error occurred while saving MDM data',
    MDM_DATA_UPLOAD_FAILED_WITH_MISMATCHED_DATA: 'Could not upload MDM data due to mismatched data. Either correct the data or delete it from the uploaded file and try again',
    MDM_DATA_UPLOAD_FAILED_WITH_INVALID_DATA: 'Could not upload MDM data due to invalid data. Either Article Id/Article Description is empty or some other records is missing',
    MDM_DATA_UPLOAD_FAILED: 'Some error occurred while uploading MDM data',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    MDM_DATA_UPLOAD_FAILED_WITH_CORRUPTED_FILE: 'Could not upload MDM data, since file is corrupted',
    MDM_DATA_UPDATE_FAILED: 'Article ID or Article Description cannot be empty',
    MDM_DATA_MAIL_FAILED: 'Error in sending mail',
    MDM_DATA_SYNC_FAILED: 'MDM data sync failed',
    MDM_DATA_MAPPING_FILE_ERROR: 'Some error occurred while reading file from S3 bucket',
    MDM_SYNC_NOT_ENABLED: 'MDM sync is not enabled',
    CREDIT_CRUNCH_NOTIFICATION: 'Failed to send credit crunch notification ',
    RESERVED_CREDIT_INSERTED: 'Failed to insert reserved credit',
    NEW_PSKU_FAILED: 'Failed to create Data',
    PSKU_UPDATE_FAILED: 'Failed to update Data',
    MRP_AND_CASELOT_CHECK_FAILURE: 'Failed to fetch MRP and caselot check details',
    SALES_ORDER_CREATION_FAILED: 'Failed to create sales order',
    MRP2_CHECK_FAILURE: 'Failed to fetch MRP2 check details',
    GST_PAN_FAILURE: 'Failed to fetch GST and PAN details',
    GST_PAN_ERROR: 'Failed to fetch GST and PAN details',
    SAP_HOLIDAY_LIST: 'Failed to fetch SAP holiday list',
    ROR_DATA_SYNC_FAILED: 'NO Data available',
    SAP_HOLIDAY_DATA_UPLOAD_FAILED_WITH_CORRUPTED_FILE: 'Could not upload sap holiday file, since file is corrupted',
    SAP_HOLIDAY_LIST_UPDATE: 'Failed to update SAP holiday list',
    INVALID_FILE_FORMAT: 'Please upload the file with columns in the following sequence: Year, State Code, State Description, Holiday Date.',
    AMENDMENT_DETAILS_FETCH_ERROR: 'Failed to fetch amendment details',
    AMENDMENT_CREATE_ERROR: 'Error while creating amendment',
    MULE_API_FAILED: 'Mule API failed to give success response',
    AUTO_CLOSURE_SYNC_FAILED: 'Auto closure data sync failed',
    VALIDATE_PAYLOAD: 'Failed to validate payload',
    VALIDATE_ORDER: 'Failed to validate order',
    VALIDATE_REGULAR: 'Failed to validate regular order',
    SAVE_ORDER: 'Failed to save order in database',
    VALIDATE_RUSH: 'Failed to validate rush order',
    VALIDATE_SELF_LIFTING: 'Failed to validate self lifting order',
    VALIDATE_BULK: 'Failed to validate bulk order',
    VALIDATE_LIQUIDATION: 'Failed to validate liquidation order',
    RUSH_ORDER_PDP_ERROR:
        'This item is not subject to PDP restrictions and therefore cannot be processed as a Rush Order. Please proceed by placing it as a Regular Order or Auto Order.',
    RUSH_ORDER_CMIR_ERROR: 'This item is flagged as CMIR and therefore cannot be processed as a Rush Order. Please proceed by placing it as a Regular Order or Auto Order.',
    REGULAR_INSTEAD_OF_ARS: 'Order cannot be placed as ARS flags are enabled and non-salt items are present. Please place an AUTO-ORDER.',
    UPDATE_ORDER: 'Failed to save create order data in database',
    CREATE_REGULAR: 'Failed to create regular order',
    CREATE_ORDER: 'Failed to create order',
    PO_UNDER_SUBMISSION_PROCESSING: 'Order submission is already in progress for this PO',
};
