export const SuccessMessage = {
    'PRODUCT_SYNC_SUCCESS': 'Product Master Data synced successfully',
    'DISTRIBUTOR_SYNC_SUCCESS': 'Distributor Master Data synced successfully',
    'WAREHOUSE_DETAILS_SUCCESS': 'Successfully fetched ship to and unloading points',
    'OPEN_SO_SYNC_SUCCESS': 'Open SO Data synced successfully',
    'GET_SALES_ORDER_DELIVERY': 'Successfully fetched sales order delivery',
    'GET_SALES_ORDER_INVOICE': 'Successfully fetched sales order invoice',
    'SO_DETAILS_FETCH_SUCCESS': 'Successfully fetch sales order details',
    'SALES_HIERARCHY_SYNC_SUCCESS': 'Sales hierarchy details updated successfully',
    'DOWNLOAD_SALES_SUCCESS': 'Sales details fetched successfully',
    'PRODUCT_DISTRIBUTOR_MAPPING_SUCCESS': 'Products are mapped to distributors successfully',
    'MATERIALS_BOUM_EXPLODE_SUCCESS': 'Successfully fetched materials BOM explode',
    'REQUEST_CATEGORY_FETCH_SUCCESS': 'Service request categories fetched successfully',
    'REQUEST_CATEGORY_CREATE_SUCCESS': 'Request service category added successfully',
    'REQUEST_CATEGORY_UPDATE_SUCCESS': 'Request service category modified successfully',
    'USER_CREATE_SUCCESS': 'Users added successfully',
    'MAPPING_REQUEST_CREATE_SUCCESS': 'Mapping request created successfully',
    'MAPPING_REQUEST_LIST_SUCCESS': 'Mapping request fetched successfully',
    'DISTRIBUTOR_MAPPED_SUCCESS': 'Distributor mapped successfully',
    'DISTRIBUTOR_MAPPING_REQUEST_UPDATE_SUCCESS': 'Distributor mapping request updated successfully',
    'GET_TSE_LIST_SUCCESS': 'Tse list fetched successfully',
    'EMAIL_ID_UPDATED_SUCCESSFULLY': 'Email Id updated successfully',
    'MOBILE_NUMBER_UPDATED_SUCCESSFULLY': 'Mobile Number updated successfully',
    'OTP_SEND_SUCESSFULLY': 'OTP Sent successfully',
    'MAIL_SENT': 'Email sent for verification, please check your email and verify',
    'PLANT_REQUEST_LIST_SUCCESS': 'Plant request fetched successfully',
    'PDP_UPDATE_REQUEST_SUCCESS': 'PDP update request saved successfully',
    'PDP_UPDATE_REQUESTS_FETCH_SUCCESS': 'PDP update request list fetched successfully',
    'PDP_UPDATE_RESPONSE_SUCCESS': 'PDP updated successfully',
    'CUSTOMER_GROUP_DETAILS_SUCCESS': 'Customer group details fetched successfully',
    'MDM_DATA_FETCHED_SUCCESSFULLY': 'MDM data fetched successfully',
    'MDM_DATA_DOWNLOADED_SUCCESSFULLY': 'MDM data Downloaded successfully',
    'MDM_DATA_SAVED_SUCCESSFULLY': 'MDM data saved successfully',
    'MDM_DATA_UPLOADED_SUCCESSFULLY': "MDM data uploaded successfully",
    'MDM_DATA_MAIL_SUCCESSFULLY': "Mail sent successfully",
    "MDM_DATA_SYNC_SUCCESSFULLY": "MDM data synced successfully",
    'CREDIT_CRUNCH_NOTIFICATION': 'Credit crunch notification sent successfully',
    'RESERVED_CREDIT_INSERTED': 'Reserved credit inserted successfully',
    'NEW_PSKU_CREATED': 'Data created successfully',
    'PSKU_UPDATED_SUCCESSFULLY': 'Data updated successfully',
    'MRP_AND_CASELOT_CHECK_SUCCESS': 'MRP and caselot check details fetched successfully',
    'SALES_ORDER_CREATED_SUCCESSFULLY': 'Sales order created successfully',
    'MRP2_CHECK_SUCCESS': 'MRP2 details fetched successfully',
    'GST_PAN_SUCCESS':'GST and PAN details fetched successfully',
    'SAP_HOLIDAY_LIST': 'SAP holiday list fetched successfully',
    "ROR_DATA_SYNC_SUCCESSFULLY": "ROR data synced successfully",
    'SAP_HOLIDAY_LIST_UPDATE': 'SAP holiday list updated successfully',
    'AMENDMENT_DETAILS_FETCH_SUCCESS' : 'Amendment details fetched successfully',
    'AMENDMENT_CREATED_SUCCESSFULLY' : 'Amendment created successfully',
    'AUTO_CLOSURE_SYNC_SUCCESSFULLY': 'Auto closure data synced successfully',
    'VALIDATE_ORDER': 'Order validated successfully',
    'SAVE_ORDER': 'Order saved successfully in database',
    'CREATE_ORDER': 'Order created successfully',
}