const env = process.env.REACT_APP_STAGE || 'dev';
let ga_id = process.env.REACT_APP_GA_ID || env === 'prod' ? 'G-S5FNBMXE5G' : env === 'uat' ? 'G-HB7QJQ6D8C' : 'G-57SC0VBZ1E';
let cache_version = process.env.REACT_APP_CACHE_VERSION || 20241113000000;

const baseUrl = process.env.REACT_APP_BASE_URL;
const authUrl = baseUrl && baseUrl.length != 0 ? baseUrl : process.env.REACT_APP_AUTH_BASE_URL;
const orderUrl = baseUrl && baseUrl.length != 0 ? baseUrl : process.env.REACT_APP_ORDER_BASE_URL;
const sapUrl = baseUrl && baseUrl.length != 0 ? baseUrl : process.env.REACT_APP_SAP_BASE_URL;
const mtecomUrl = baseUrl && baseUrl.length != 0 ? baseUrl : process.env.REACT_APP_MT_ECOM_BASE_URL;
const syncJobUrl = baseUrl && baseUrl.length != 0 ? baseUrl : process.env.REACT_APP_SYNC_JOB_BASE_URL;
const creditUrl = baseUrl && baseUrl.length != 0 ? baseUrl : process.env.REACT_APP_CREDIT_BASE_URL;
const arsUrl = baseUrl && baseUrl.length != 0 ? baseUrl : process.env.REACT_APP_ARS_BASE_URL;
const arsAllocationUrl = process.env.REACT_APP_ARS_ALLOCATION_BASE_URL;
const clientId = process.env.REACT_APP_CLIENT_ID;
const poolId = process.env.REACT_APP_POOL_ID;
const domain = process.env.REACT_APP_DOMAIN;
const redirectSignIn = process.env.REACT_APP_REDIRECT_SIGN_IN;
const redirectSignOut = process.env.REACT_APP_REDIRECT_SIGN_OUT;
const recaptchaKey = process.env.REACT_APP_RECAPTCHA_KEY;

const envBased = {
    serviceServerName: {
        auth: 'auth_api_server',
        order: 'order_api_server',
        sap: 'sap_api_server',
        mtecom: 'mtecom_api_server',
        syncjob: 'sync_jobs_api_server',
        ars: 'ars_api_server',
        ars_allocation: 'ars_allocation_server',
        credit: 'credit_api_server',
    },
    auth_api_server: {
        path: '/auth',
        version: '/api/v1/',
        url: authUrl,
        register: 'register',
        login: 'login',
        validate_auth: 'validate',
        reset_password: 'reset-password',
        refresh_token: 'refresh-token',
        generate_otp: 'generate-otp',
        verify_otp: 'verify-otp',
        get_alert: 'get-alert',
        update_alert: 'update-alert',
        validate_distributor_id: 'validate-distributor-id',
        userfetch: 'user/fetch',
        users: 'users',
        user: 'user',
        changeRrole: 'user/change-role',
        encryptionKey: 'qwerty987secret',
        change_password: 'change-password',
        logout: 'logout',
        distributor_list: 'distributor-list',
        distributor_alert_comment_list: 'alert-comment-list',
        distributor_list_admin: 'admin/distributor-list',
        distributor_settings: 'admin/distributor-settings',
        alert_comment_list: 'admin/alert-comment-list',
        sessions: 'sessions',
        sso_details: 'sso-details',
        tse_user_list_admin: 'admin/tse-user-list',
        tse_user_setting: 'admin/tse-user-setting',
        fetch_app_level_settings: 'app-level-configuration',
        update_app_level_settings: 'admin/app-level-configuration',
        fetch_app_level_settings_admin: 'admin/app-level-configuration',
        sessions_admin: 'admin/sessions',
        cfa_details: 'cfa-data',
        cfa_details_admin: 'admin/cfa-data',
        get_maintenance_status: 'maintenance-status',
        add_new_maintenance: 'admin/add-maintenance-status',
        update_maintenance: 'admin/update-maintenance-status',
        azureAD_users: 'admin/fetch-azureAD-users',
        add_SSO_user: 'admin/sso_user',
        fetch_help_section_data: 'admin/fetch-help-section-data',
        get_file_from_awsS3: 'admin/get-file-from-awsS3',
        upload_file: 'admin/upload-file',
        fetch_files_history: 'admin/file-upload-history',
        update_file_status: 'admin/update-file-status',
        get_preassigned_url: 'admin/createPreAssignUrl',
        get_dashboard_filter_categories: 'admin/dashboard-filter-categories',
        area_code_list: 'admin/area-code-list',
        get_adjustment_timeline: 'admin/get-adjustment-timeline',
        get_stock_norm_config_regions: 'admin/stock-norm-config-regions',
        get_stock_norm_config_areas: 'admin/stock-norm-config-areas',
        get_stock_norm_config_divisions: 'admin/stock-norm-config-divisions',
        get_cycle_safety_stock_config: 'admin/cycle-safety-stock-config',
        update_cycle_safety_stock: 'admin/update-cycle-safety-stock',
        cfa_depot_mapping: 'admin/cfa-depot-mapping',
        db_moq_details: 'admin/db-moq-details',
        multiple_update_cfa_depot_mapping: 'admin/multiple-update-cfa-depot-mapping',
        get_depot_code: 'survey/get-depot-for-logistics',
        get_survey_satistics: 'survey/survey-response-report',
        update_cfa_question: 'survey/upsert-cfa-questionnaire-admin',
        get_cfa_questions_admin: 'survey/get-cfa-questions-admin',
        get_cfa_questions: 'survey/get-cfa-questions',
        survey_db_response: 'survey/save-db-response',
        survey_report: 'survey/survey-report',
        active_plant_distributors: 'survey/active-plant-distributors',
        active_session_report: 'admin/active-session-report',
        invalidate_session: 'admin/invalidate-session',
        insert_admin_session: 'admin/insert-session',
        get_pdp_windows_admin: 'admin/pdp-window',
        get_pdp_windows: 'pdp-window',
        upsert_pdp_window: 'admin/pdp-window',
        delete_pdp_window: 'admin/pdp-window',
        insert_pdp_unlock_request: 'admin/pdp-unlock/insert-request',
        get_pdp_unlock_requests: 'admin/pdp-unlock/fetch-requests',
        get_db_regions: 'admin/fetch-db-regions',
        get_sso_users: 'admin/fetch-sso-users',
        update_pdp_unlock_request: 'admin/pdp-unlock/update-request',
        set_expired_pdp_unlock_requests: 'admin/pdp-unlock/set-expired',
        get_pdp_unlock_window: 'admin/pdp-unlock/window-settings',
        update_pdp_unlock_window: 'admin/pdp-unlock/window-settings',
        // get_depot_code: 'survey/get-depot-for-logistics',
        save_survey_link: 'survey/survey-link',
        survey_link_response: 'survey/survey-link-response',
        save_noc_response: 'survey/save-noc',
        fetch_distributor_agreements: 'survey/fetch-distributor-agreements',
        fetch_survey_response: 'survey/fetch-survey-response',
        save_survey_response: 'survey/save-survey-response',
        fetch_auto_closure_gt_admin: 'admin/fetch-auto-closure-gt',
        fetch_auto_closure_gt: 'fetch-auto-closure-gt',
        update_auto_closure_gt: 'admin/update-auto-closure-gt',
        fetch_auto_closure_mt_ecom_single_grn: 'admin/fetch-auto-closure-mt-ecom-single-grn',
        fetch_auto_closure_mt_ecom_single_grn_customer_details: 'admin/fetch-auto-closure-mt-ecom-single-grn-customer-details',
        update_single_grn_auto_closure: '/admin/update-single-grn-auto-closure',
        fetch_multi_grn_consolidated_data: '/admin/fetch-multi-grn-consolidated-data',
        fetch_multi_grn_customer_details: 'admin/fetch-multi-grn-customer-details',
        update_multi_grn_auto_closure: 'admin/update-multi-grn-auto-closure',
        multi_update_auto_closure_gt: 'admin/multi-update-auto-closure-gt',
        multi_update_auto_closure_mt_ecom: 'admin/multi-update-mt-ecom',
        invalidate_other_sessions_admin: 'admin/invalidate-other-sessions',
        invalidate_other_sessions: 'invalidate-other-sessions',
        update_cfa_flow_calender: 'admin/update-cfa-process-calender',
        fetch_cfa_flow_calender: 'admin/fetch-cfa-process-calender',
        update_multiple_pdp_unlock_requests: 'admin/pdp-unlock/update-multiple-requests',
        insert_approved_pdp_unlock_request: 'admin/pdp-unlock/insert-approved-request',
        fetch_auto_closure_gt_report: 'admin/auto-closure-gt-report',
        fetch_auto_closure_mt_config: 'admin/fetch-auto-closure-mt-ecom-config',
        update_auto_closure_mt_config: 'admin/update-auto-closure-mt-ecom-config',
        fetch_auto_closure_mt_report: 'admin/fetch-auto-closure-mt-report',
    },

    order_api_server: {
        path: '/order',
        version: '/api/v1/',
        url: orderUrl,
        warehouse_details: 'warehouses',
        warehouse_details_admin: 'admin/warehouses',
        get_materials: 'materials',
        get_materials_admin: 'admin/materials',
        get_market_name: 'fetch/market',
        get_all_materials: 'materials',
        get_order_list: 'orders',
        get_order_list_admin: 'admin/orders',
        distributor_profile: 'distributor/profile',
        distributor_profile_admin: 'admin/distributor/profile',
        poDetails: 'po-details',
        get_sync_logs: 'admin/sync-logs',
        update_material_tags: 'util/update-material-tags',
        poDetailsAdmin: 'admin/po-details',
        download_sample_tag: 'admin/material-tags',
        remove_draft: 'remove-draft',
        remove_draft_by_admin: 'admin/remove-draft',
        remove_expired_carts: 'remove-expired-carts',
        get_zone_wise_orders: 'admin/get-zone-wise-orders',
        get_zone_wise_orders_by_order_type: 'admin/get-zone-wise-orders-by-order-type',
        get_category_wise_portal_issues: 'admin/get-category-wise-reported-issues',
        sdr_list_admin: 'admin/sdr-list',
        service_delivery_request: 'service-delivery-request',
        service_delivery_request_admin: 'admin/service-delivery-request',
        sdr_report_data: 'admin/sdr-report-data',
        sd_response_report_data: 'admin/sd-response-report-data',
        sku_codes: 'admin/sku-codes',
        sku_details: 'admin/sku-details',
        customer_groups: 'admin/customer-groups',
        save_rule_config: 'admin/save-rule-config',
        get_rule_config: 'admin/fetch-rule-config',
        get_ro_requests: 'rush-order/get-requests',
        get_ro_approval_count: 'rush-order/get-approval-count',
        promised_credit: 'promised-credit',
        sent_order_request_admin: 'rush-order/admin/send-request',
        sent_order_request: 'rush-order/send-request',
        update_ro_request: 'rush-order/update-request',
        brand_variant_combinations: 'admin/brand-variant-combinations',
        brand_variant_details: 'admin/brand-variant-details',
        brand_variant_prioritization: 'admin/brand-variant-prioritization',
        prioritization_list: 'admin/fetch-prioritization',
        bo_moq_mapping_data: 'admin/bo-moq-mapping-data',
        bulk_order_update_moq: 'admin/bo-update-moq',
        bo_mapped_zone: 'admin/bo-get-mapped-area-zone',
        bo_mass_update: 'admin/bo-mass-update-moq',
        get_order_request: 'admin/get-order-request',
        set_ro_expired: 'rush-order/set-expired',
        getBoMoq: 'admin/bo-get-moq',
        approve_ro_request: 'rush-order/update-request-approved',
        ro_reasons: 'rush-order/request-reasons',
        ro_approval_email: 'rush-order/admin/send-approval-email',
        get_non_forecasted_psku: 'admin/fetch-non-forecasted-sku',
        all_db_list: 'admin/all-db-list',
        upsert_non_forecasted_psku: 'admin/upsert-non-forecasted-sku',
        upsert_all_non_forecast: 'admin/upsert-all-non-forecasted-sku',
        update_ro_request2: 'rush-order/update-request2',
        distributor_upcoming_pdp_date: 'get-upcoming-pdp-days',
        upsert_all_rule_configuration: 'admin/upsert-all-rule-configuration',
        upsert_rule_configuration: 'admin/upsert-rule-configuration',
        mass_update_ro_request: 'rush-order/update-multiple-requests',
        fetch_plant_details: 'admin/fetch-plant-details',
        ro_ars_window_check: 'rush-order/ars-window-check',
    },

    sap_api_server: {
        path: '/sap',
        version: '/api/v1/',
        url: sapUrl,
        warehouse_details: 'warehouse-details',
        warehouse_details_dist_channel: 'warehouse-details-dist-channel',
        warehouse_details_admin: 'admin/warehouse-details',
        warehouse_details_dist_channel_admin: 'admin/warehouse-details-dist-channel',
        create_order: 'create-order',
        validate_order: 'validate-order',
        re_order: 're-order',
        credit_limit: 'credit-limit',
        credit_limit_admin: 'admin/credit-limit',
        sales_order: 'so-details',
        sales_order_delivery: 'sales-order-delivery',
        sales_order_invoice: 'sales-order-invoice',
        sales_order_admin: 'admin/so-details',
        sales_order_delivery_admin: 'admin/sales-order-delivery',
        sales_order_invoice_admin: 'admin/sales-order-invoice',
        material_sync: 'util/product-sync',
        distributor_sync: 'util/distributor-sync',
        sales_hierarchy_sync: 'util/sales-hierarchy-sync',
        multiple_so_details: 'multiple-so-details',
        multiple_so_details_admin: 'admin/multiple-so-details',
        so_sync: 'util/so-sync',
        mdm_sync: 'util/mdm-sync',
        report_portal_error: 'report-portal-error',
        materials_bom_explode: 'materials-bom-explode',
        create_order_admin: 'admin/create-order',
        validate_order_admin: 'admin/validate-order',
        re_order_admin: 'admin/re-order',
        distributor_inventory_sync: 'util/distributor-inventory-sync',
        service_request_category: 'service-request-category',
        report_portal_error_admin: 'admin/report-portal-error',
        get_liquidation_materials: 'get-liquidation-materials',
        get_liquidation_materials_admin: 'admin/get-liquidation-materials',
        get_mapping_requests: 'admin/get-mapping-requests',
        create_mapping_request: 'admin/create-mapping-requests',
        update_mapping_request: 'admin/update-mapping-requests',
        get_distributor_code: 'admin/get-distributor-code',
        tse_list: 'admin/tse-list',
        update_distributor_email: 'admin/update-distributor-email',
        update_distributor_mobile: 'admin/update-distributor-mobile',
        send_otp_mail_update: 'auth/send-otp-mail-mobile',
        email_verify: 'auth/verify-email',
        verify_otp_update_mobile: 'auth/verify-mobile',
        fetch_service_request_category: 'admin/service-request-category',
        report_portal_error_cfa: 'admin/report-portal-error-cfa',
        sap_material_list: '/admin/sap-material-list',
        update_plant_code_mapping: 'admin/plant-code-update-request',
        getPlantCodeRequestList: 'admin/get-plant-code-update-request',
        Logistic_Officer_Response: 'admin/logistic-Officer-Response',
        pdp_update_reqeust: 'admin/pdp-update-request',
        pdp_update_request_list: 'admin/get-pdp-update-requests',
        pdp_request_response: 'admin/pdp-update-response',
        customer_groups: 'admin/customer-group-list',
        update_plant_code: 'admin/update-distributor-plant-code',
        depot_code_mapping: 'admin/depot-code-mapping-details',
        download_Mdm_Data: 'admin/download-mdm-data',
        get_mdm_data: 'admin/get-mdm-data',
        mdm_filed_level_save: 'admin/mdm-filed-level-save',
        upload_mdm_data: 'admin/upload-mdm-data',
        all_mdm_customers: 'admin/all-mdm-customers',
        insert_reserved_credit_admin: 'admin/insert-reserved-credit',
        insert_reserved_credit: 'auth/insert-reserved-credit',
        add_update_sku: 'admin/add-update-sku',
        add_new_sku: 'admin/add-new-sku',
        cleartax_gst_pan: 'admin/cleartax-gstpan',
        sap_holiday_list: 'get-sap-holidays',
        update_sap_holidays: 'admin/sap-holiday-sync',
        validate_order_be: 'validate-order2',
        validate_order_admin_be: 'admin/validate-order2',
        create_order_be: 'create-order2',
        create_order_admin_be: 'admin/create-order2',
    },
    mtecom_api_server: {
        path: '/mt-ecom',
        version: '/api/v1/',
        url: mtecomUrl,
        po_list: 'mt-ecom-poList',
        po_Items: 'mt-ecom-poItem',
        upload_reliance: 'mt-ecom-upload',
        rdd_list: 'mt-ecom-rdd-list',
        customer_list: 'mt-ecom-customer-list',
        add_update_customer: 'mt-ecom-add-customer',
        create_amendment: 'mt-ecom-add-rdd',
        rdd_item_list: 'mt-ecom-rdd-item-list',
        customer_workflow_list: 'mt-ecom-customer-workflow-list',
        add_update_workflow_workflow: 'mt-ecom-add-customer-workflow',
        customer_workflow_data: 'mt-ecom-customer-workflow',
        so_sync: 'mt-ecom-so-sync',
        customer_code_list: 'mt-ecom-customer-codes',
        add_update_kams: 'mt-ecom-add-kams',
        get_kams_data: 'mt-ecom-get-kams',
        download_mt_reports: 'po/mt-ecom-reports',
        shopify_po_list: 'shopify/shopify-po-list',
        shopify_po_items: 'shopify/shopify-po-items',
        shopify_reports: 'shopify/shopify-reports',
        export_data: 'po/export-po-data',
        shopify_retrigger: 'shopify/shopify-req-res',
        mtecom_retrigger: 'mt-ecom-retrigger-so',
        shopify_z_table_export: 'shopify/z-table-reports',
        shopify_all_customers: 'shopify/all-shopify-customers',
        resend_po: 'shopify/resend-po',
        delete_items: 'shopify/delete-items',
        update_customer_data: 'mt-ecom-edit-kams',
        download_po: 'po/mt-ecom-download-po',
        download_po_details: 'po/mt-ecom-download-po-details',
        asn_download: 'invoice/asn-download',
        mt_ecom_tot_tolerance: 'mt-tot-tolerance',
        download_so_req_res: 'po/download-so-req-res',
    },
    sync_jobs_api_server: {
        path: '/sync-jobs',
        version: '/api/v1/',
        url: syncJobUrl,
        //unused path should be removed from sap_server later
        material_sync: 'util/product-sync',
        distributor_sync: 'util/distributor-sync',
        sales_hierarchy_sync: 'util/sales-hierarchy-sync',
        distributor_inventory_sync: 'util/distributor-inventory-sync',
        dlp_sync: 'automated-ars-validation',
        set_ro_expired: 'set-expired',
        cfa_process_flow: 'admin/get-cfa-process-logs',
        so_sync: 'mt-ecom-so-sync',
        nourishco_planning_sync: 'admin/nourishco-planning-sync',
        download_nourishco_planning: 'admin/download-nourishco-planning-sync',
        delivery_code_reports: 'admin/delivery-code-reports',
    },
    ars_api_server: {
        path: '/arsservice',
        version: '/api/v1/',
        url: arsUrl,
        brand_variant_list: 'admin/brand-variant-list',
        regional_brands: 'admin/regional-brand-list',
        forecast: 'admin/forecast',
        forecast_summary: 'admin/forecast-summary',
        download_forecast_summary: 'admin/download-forecast-summary',
        update_forecast: 'admin/update-forecast',
        forecast_configuration: 'admin/forecast-configuration',
        last_forecast_date: 'admin/last-forecast-date',
        submit_forecast: 'admin/submit-forecast',
        fetch_forecast_for_dist: 'fetch-forecast-for-dist',
        fetch_forecast_for_dist_admin: 'admin/fetch-forecast-for-dist',
        update_forecast_distribution: 'admin/update-forecast-distribution',
        stock_data: 'admin/stock-data',
        stock_sync_time: 'admin/stock-sync-time',
        sku_stock_data: 'admin/sku-stock-data',
        stock_norm_audit: 'admin/stock-norm-audit',
        moq_mapping_data: 'admin/moq-mapping-data',
        update_moq: 'admin/update-moq',
        distributor_moq: 'distributor-moq',
        stock_norm_default: 'admin/stock-norm-default',
        all_ars_tolerance: 'admin/all-ars-tolerance',
        ars_tolerance_admin: 'admin/ars-tolerance',
        ars_tolerance: 'ars-tolerance',
        get_excluded_psku_admin: 'admin/excluded-materials',
        get_excluded_psku: 'excluded-materials',
        update_quantity_norm: 'admin/update-quantity-norm',
        upload_forecast: 'admin/upload-forecast',
        dlp_sync: 'automated-ars-validation',
        dlp_download: 'admin/download-dlp-report',
        stock_norm_db_filter: 'admin/stock-norm-db-filter',
        upsert_soq_norms: 'admin/upsert-soq-norms',
        fetch_soq_norms: 'admin/fetch-soq-norms',
        fetch_soq_norm_division_list: 'admin/fetch-soq-division-list',
        delete_soq_norm: 'admin/delete-soq-norms',
        update_sku_soq_norm_sync: 'admin/sku-soq-norm-sync',
        update_db_pop_class: 'admin/db-pop-class',
        upload_stock_norm: 'admin/upload-stock-norm',
        fetch_ars_configurations: 'admin/ars-configurations', // These 2 are left to change in action
        update_ars_configurations: 'admin/update-ars-configurations',
        psku_tolerance_exclusions: 'psku-tolerance-exclusions',
        psku_tolerance_exclusions_admin: 'admin/psku-tolerance-exclusions',
        update_psku_tolerance_exclusions: 'admin/psku-tolerance-exclusions',
        upload_region_forecast: 'admin/upload-region-forecast',
        forecast_distribution: 'admin/forecast-distribution',
        ars_recommendation_simulation: 'test-fetch-forecast-for-dist',
        upsert_db_psku_tolerance: 'admin/upsert-distributor-psku-tolerance',
        product_hierarchy_filter: 'admin/product-hierarchy-filter',
        fetch_distributor_psku_tolerance_admin: 'admin/fetch-distributor-psku-tolerance',
        fetch_distributor_psku_tolerance: 'fetch-distributor-psku-tolerance',
        missing_distributor_psku_combination: 'admin/missing-distributor-psku-combination',
        delete_distributor_psku_tolerance: 'admin/delete-distributor-psku-tolerance',
        fetch_original_distributor_psku_tolerance: 'admin/fetch-original-distributor-psku-tolerance',
        aos_audit_report: 'admin/aos-audit-report',
        insert_sync_log: 'admin/insert-sync-log',
        download_stock_norm: 'admin/download-stock-norm',
        ars_enabled_area_codes: 'admin/ars-enabled-area-codes',
        stock_norm_for_distributor: 'admin/stock-norm-for-distributor',
        forecast_dump_details: 'admin/forecast-dump-details',
    },

    credit_api_server: {
        path: '/credit',
        version: '/api/v1/',
        url: creditUrl,
        send_credit_extension_request: 'admin/send-credit-extension-request',
        get_mt_customer_details: 'admin/get-user-mapping-list',
        transaction_summary: 'admin/get-credit-extention-request',
        transaction_details: 'admin/get-order-request',
        cl_approver_update: 'admin/update-request',
        cl_finance_approver: 'admin/get-cl-approver-finance',
        // download_baselimit: 'admin/base-limit-download-excel',
        customer_groups: 'admin/customer-groups',
        account_master_list: 'admin/account-list',
        credit_limit_admin: 'admin/credit-limit',
        upload_base_limit: 'util/update-credit-limit',
        cl_sales_approver: 'admin/get-cl-approver-sales',
        get_approver_details: 'admin/get-approver-details',
        update_approver_details: 'admin/insert-approver-details',
        get_risk_category: 'admin/get-risk-category',
        get_latest_upload_record: 'admin/account-base-limit-check',
        fetch_approvers: 'admin/fetch-approver-details',
        add_approver_config: 'admin/add-approver-config',
        get_category_list: 'admin/get-category-list',
        fetch_unmapped_group: 'admin/fetch-unmapped-cg',
        upload_gt_requests: 'admin/excel-gt-requests',
        gt_transaction_summary: 'admin/get-gt-credit-extention-requests',
        gt_transaction_details: 'admin/get-gt-request-details',
        fetch_mt_cl_report: 'admin/get-mt-cl-report',
        add_GT_approvers: 'admin/add-gt-approvers',
        get_cluster: 'admin/get-cluster',
        get_GT_approvers: 'admin/get-gt-approver-details',
        cl_gt_approver_update: 'util/gt-update-request',
        gt_download_excel: 'util/get-gt-excel-data',
        get_gt_approver: 'util/get-gt-approvers',
        get_gt_requestor: 'admin/get-gt-requestor-details',
        gt_requestor_details: 'admin/fetch-gt-add-requestor',
        add_gt_requestor: 'admin/add-gt-requestor',
        get_requestor_clusters: 'admin/get-requestor-clusters',
        get_customer_groups: 'admin/get-customer-group-for-settings',
        fetch_gt_cl_report: 'admin/get-gt-cl-report',
    },

    ars_allocation_server: {
        path: '/forecast',
        version: '/',
        url: arsAllocationUrl,
        forecast_dump: 'ars-sync',
        allocation: 'forecast-dump-post-program-apis',
        phasing: 'uniform-forecast-phasing',
    },

    google_analytics_id: ga_id,
    cache_version,
    app_environment: env,
    sso_login: {
        provider: '', //'Dev-Pegasus-AzureCognito-Idp',
        userPoolId: poolId,
        userPoolWebClientId: clientId,
        domain: domain,
        scope: ['email', 'openid', 'aws.cognito.signin.user.admin'],
        redirectSignIn: redirectSignIn,
        redirectSignOut: redirectSignOut,
        region: 'ap-south-1',
        responseType: 'token',
    },
    recaptchaKey: recaptchaKey,
};

const config = {
    // Add common config values here
    DUMMY_VALUE: 5000000,

    // Default to dev if not set
    ...envBased,
};
export default config;
